In [ ]:
#google drive의 COSE362-term-project/final_dataset 폴더와 연결
from google.colab import drive

drive.mount('/content/drive')

!ls /content/drive/MyDrive/COSE362-term-project/final_dataset

import sys

sys.path.append('/content/drive/MyDrive/COSE362-term-project/final_dataset')

import os

os.chdir("/content/drive/MyDrive/COSE362-term-project/final_dataset")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
africa_shape.csv	     crop_groupped.csv	     landuse_2019.csv
All_Countries_HIV_Rates.csv  disease_indexing.ipynb  livestock_counts.csv
combining.ipynb		     landuse_2015.csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
disease_df = pd.read_csv("All_Countries_HIV_Rates.csv")
standard_df = pd.read_csv("africa_shape.csv")

In [ ]:
disease_df

     year       country        region_name  infection_rate
0    2010  Burkina Faso  Boucle de Mouhoun        0.585652
1    2010  Burkina Faso           Cascades        0.979432
2    2010  Burkina Faso             Centre        1.955671
3    2010  Burkina Faso         Centre-Est        1.037736
4    2010  Burkina Faso        Centre-Nord        0.379147
..    ...           ...                ...             ...
678  2015        Angola            Malanje        2.241379
679  2015        Angola             Moxico        4.166667
680  2015        Angola             Namibe        1.747312
681  2015        Angola               Uíge        1.226994
682  2015        Angola              Zaire        0.409836

[683 rows x 4 columns]

In [ ]:
standard_df

,FID,ADM1_CODE,ADM1_NAME,ADM0_CODE,ADM0_NAME,CONTINENT,REGION
0,afr_g2014_2013_1.1,124,Administrative unit not available,102,Abyei,Africa,NaN
1,afr_g2014_2013_1.2,341,Adrar,4,Algeria,Africa,Northern Africa
2,afr_g2014_2013_1.3,342,Ain-Defla,4,Algeria,Africa,Northern Africa
3,afr_g2014_2013_1.4,343,Ain-Temouchent,4,Algeria,Africa,Northern Africa
4,afr_g2014_2013_1.5,344,Alger,4,Algeria,Africa,Northern Africa
...,...,...,...,...,...,...,...
854,afr_g2014_2013_1.855,147335,Souss - Massa - Draâ,169,Morocco,Africa,Northern Africa
855,afr_g2014_2013_1.856,147336,Tadla - Azilal,169,Morocco,Africa,Northern Africa
856,afr_g2014_2013_1.857,147337,Tanger - Tétouan,169,Morocco,Africa,Northern Africa
857,afr_g2014_2013_1.858,147338,Taza - Al Hoceima - Taounate,169,Morocco,Africa,Northern Africa
858,afr_g2014_2013_1.859,190430,Bas Sassandra,66,Côte d'Ivoire,Africa,Western Africa

disease_df에서 이용된 country, region set 뽑아내기

In [ ]:
disease_df[['country','region_name']]

          country        region_name
0    Burkina Faso  Boucle de Mouhoun
1    Burkina Faso           Cascades
2    Burkina Faso             Centre
3    Burkina Faso         Centre-Est
4    Burkina Faso        Centre-Nord
..            ...                ...
678        Angola            Malanje
679        Angola             Moxico
680        Angola             Namibe
681        Angola               Uíge
682        Angola              Zaire

[683 rows x 2 columns]

In [ ]:
disease_country_set = set(disease_df['country'])
disease_country_list = list(set(disease_df['country']))
#len(set(disease_df['country']))

disease_country_list

['Burkina Faso',
 'Senegal',
 'Liberia',
 'Ghana',
 'Mali',
 'Guinea',
 'South Africa',
 'Sierra Leone',
 'Zimbabwe',
 'Ethiopia',
 'Eswatini',
 'Burundi',
 "Côte D'Ivoire",
 'Malawi',
 'Gabon',
 'Uganda',
 'Namibia',
 'Rwanda',
 'Togo',
 'Angola',
 'Congo',
 'Cameroon',
 'Sao Tome And Principe',
 'Mozambique',
 'Lesotho',
 'Zambia',
 'Congo Democratic Republic',
 'Niger',
 'Kenya',
 'Tanzania',
 'Chad',
 'Gambia']

In [ ]:
standard_country_set = set(standard_df['ADM0_NAME'])
standard_country_list = list(standard_country_set)

standard_country_set

{'Abyei',
 'Algeria',
 'Angola',
 'Benin',
 'Botswana',
 'Burkina Faso',
 'Burundi',
 'Cameroon',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Comoros',
 'Congo',
 "Côte d'Ivoire",
 'Democratic Republic of the Congo',
 'Djibouti',
 'Egypt',
 'Equatorial Guinea',
 'Eritrea',
 'Ethiopia',
 'Gabon',
 'Gambia',
 'Ghana',
 'Guinea',
 'Guinea-Bissau',
 "Hala'ib triangle",
 'Ilemi triangle',
 'Kenya',
 'Lesotho',
 'Liberia',
 'Libya',
 "Ma'tan al-Sarra",
 'Madagascar',
 'Malawi',
 'Mali',
 'Mauritania',
 'Mauritius',
 'Morocco',
 'Mozambique',
 'Namibia',
 'Niger',
 'Nigeria',
 'Rwanda',
 'Sao Tome and Principe',
 'Senegal',
 'Seychelles',
 'Sierra Leone',
 'Somalia',
 'South Africa',
 'South Sudan',
 'Sudan',
 'Swaziland',
 'Togo',
 'Tunisia',
 'Uganda',
 'United Republic of Tanzania',
 'Western Sahara',
 'Zambia',
 'Zimbabwe'}

In [ ]:
disease_country_set - standard_country_set

# {disease : standard} mapping
# 'Congo Democratic Republic' : 'Democratic Republic of the Congo'
# "Côte D'Ivoire" : "Côte d'Ivoire"
# 'Eswatini' : 'Swaziland'
# 'Sao Tome And Principe' : 'Sao Tome and Principe'
# 'Tanzania' : 'United Republic of Tanzania'

{'Congo Democratic Republic',
 "Côte D'Ivoire",
 'Eswatini',
 'Sao Tome And Principe',
 'Tanzania'}

## **disease의 country name 중 standard country name과 안 맞는 경우**

### {disease : standard} mapping
- 'Congo Democratic Republic' : 'Democratic Republic of the Congo'
- "Côte D'Ivoire" : "Côte d'Ivoire"
- 'Eswatini' : 'Swaziland'
- 'Sao Tome And Principe' : 'Sao Tome and Principe'
- 'Tanzania' : 'United Republic of Tanzania'



우선 country name부터 일치시키기

disease 중 country가 저 5개인 경우 standard 버전으로 변환하기

disease : standard dictionary를 만들어서 key값일 경우 value로 값을 변환하는 방식으로..

In [ ]:
# 딕셔너리 생성
country_mapping_dict = {
    'Congo Democratic Republic' : 'Democratic Republic of the Congo',
    "Côte D'Ivoire" : "Côte d'Ivoire",
    'Eswatini' : 'Swaziland',
    'Sao Tome And Principe' : 'Sao Tome and Principe',
    'Tanzania' : 'United Republic of Tanzania'
}

# 테스트
country_mapping_dict['Congo Democratic Republic']
for i in country_mapping_dict.keys():
  print(country_mapping_dict[i])

test = 'Eswatini'

if test in list(country_mapping_dict.keys()):
  print(country_mapping_dict[test])

Democratic Republic of the Congo
Côte d'Ivoire
Swaziland
Sao Tome and Principe
United Republic of Tanzania
Swaziland

In [ ]:
# 딕셔너리와 replace 이용하기..
# df['country'] = df['country'].replace(country_mapping)

disease_df['country'] = disease_df['country'].replace(country_mapping_dict)
set(disease_df['country'])

{'Angola',
 'Burkina Faso',
 'Burundi',
 'Cameroon',
 'Chad',
 'Congo',
 "Côte d'Ivoire",
 'Democratic Republic of the Congo',
 'Ethiopia',
 'Gabon',
 'Gambia',
 'Ghana',
 'Guinea',
 'Kenya',
 'Lesotho',
 'Liberia',
 'Malawi',
 'Mali',
 'Mozambique',
 'Namibia',
 'Niger',
 'Rwanda',
 'Sao Tome and Principe',
 'Senegal',
 'Sierra Leone',
 'South Africa',
 'Swaziland',
 'Togo',
 'Uganda',
 'United Republic of Tanzania',
 'Zambia',
 'Zimbabwe'}

## **disease의 country name과 standard country name이 일치하는지 테스트하기**

In [ ]:
set(disease_df['country'])-standard_country_set

set()

In [ ]:
new_disease_country_set = set(disease_df['country'])
new_disease_country_set-standard_country_set
#disease_country_set-standard_country_set

set()

## **disease의 region name 중 standard region name과 안 맞는 경우 찾기**

In [ ]:
new_disease_country_set

{'Angola',
 'Burkina Faso',
 'Burundi',
 'Cameroon',
 'Chad',
 'Congo',
 "Côte d'Ivoire",
 'Democratic Republic of the Congo',
 'Ethiopia',
 'Gabon',
 'Gambia',
 'Ghana',
 'Guinea',
 'Kenya',
 'Lesotho',
 'Liberia',
 'Malawi',
 'Mali',
 'Mozambique',
 'Namibia',
 'Niger',
 'Rwanda',
 'Sao Tome and Principe',
 'Senegal',
 'Sierra Leone',
 'South Africa',
 'Swaziland',
 'Togo',
 'Uganda',
 'United Republic of Tanzania',
 'Zambia',
 'Zimbabwe'}

## **Angola에 대해서 region_name mapping 진행**

In [ ]:
# Angola
angola_df = disease_df[disease_df['country']=='Angola']
print("disease data")
print(angola_df)

standard_angola_df = standard_df[standard_df['ADM0_NAME']=='Angola']

disease_angola_region = set(angola_df['region_name'])
standard_angola_region = set(standard_angola_df['ADM1_NAME'])

print(disease_angola_region - standard_angola_region)
print(standard_angola_region - disease_angola_region)

#mapping
# 'Cuanza Norte' : 'Kuanza Norte'
# 'Bié' : 'Bie'
# 'Huíla' : 'Huila'
# 'Uíge' : 'Uige'

angola_mapping_dict = {
    'Cuanza Norte' : 'Kuanza Norte',
    'Bié' : 'Bie',
    'Huíla' : 'Huila',
    'Uíge' : 'Uige'
}

disease_df.loc[disease_df['country'] == 'Angola', 'region_name'] = disease_df.loc[disease_df['country'] == 'Angola', 'region_name'].replace(angola_mapping_dict)

print("disease data after mapping")
new_angola_df = disease_df[disease_df['country']=='Angola']
print(new_angola_df)

set(new_angola_df['region_name']) - standard_angola_region

disease data
     year country     region_name  infection_rate
665  2015  Angola           Bengo        1.600000
666  2015  Angola        Benguela        1.422475
667  2015  Angola             Bié        1.909722
668  2015  Angola         Cabinda        0.913242
669  2015  Angola  Cuando Cubango        5.253940
670  2015  Angola    Cuanza Norte        2.782609
671  2015  Angola      Cuanza Sul        1.562500
672  2015  Angola          Cunene        6.278714
673  2015  Angola          Huambo        0.990099
674  2015  Angola           Huíla        1.146497
675  2015  Angola          Luanda        1.789137
676  2015  Angola     Lunda Norte        2.973978
677  2015  Angola       Lunda Sul        3.470032
678  2015  Angola         Malanje        2.241379
679  2015  Angola          Moxico        4.166667
680  2015  Angola          Namibe        1.747312
681  2015  Angola            Uíge        1.226994
682  2015  Angola           Zaire        0.409836
{'Cuanza Norte', 'Bié', 'Huíla', 'Uíge'}
{'Huila', 'Uige', 'Kuanza Norte', 'Bie'}
disease data after mapping
     year country     region_name  infection_rate
665  2015  Angola           Bengo        1.600000
666  2015  Angola        Benguela        1.422475
667  2015  Angola             Bie        1.909722
668  2015  Angola         Cabinda        0.913242
669  2015  Angola  Cuando Cubango        5.253940
670  2015  Angola    Kuanza Norte        2.782609
671  2015  Angola      Cuanza Sul        1.562500
672  2015  Angola          Cunene        6.278714
673  2015  Angola          Huambo        0.990099
674  2015  Angola           Huila        1.146497
675  2015  Angola          Luanda        1.789137
676  2015  Angola     Lunda Norte        2.973978
677  2015  Angola       Lunda Sul        3.470032
678  2015  Angola         Malanje        2.241379
679  2015  Angola          Moxico        4.166667
680  2015  Angola          Namibe        1.747312
681  2015  Angola            Uige        1.226994
682  2015  Angola           Zaire        0.409836

set()

#**남은 31개의 나라에 대해서 효율적으로 지역명 매핑하기..**

1. angola 처리 이후 mismatch 쌍 203개
2. burkina 처리 이후 mismatch 쌍 193개
3. burundi 처리 이후 mismatch 쌍 180개
4. cameroon 처리 이후 mismatch 쌍 164개
5. chad 처리 이후 mismatch 쌍 151개
6. congo 처리 이후 mismatch 쌍 146개
7. Côte d'Ivoire 삭제 이후 mismatch 쌍 130개
8. Democratic Republic of the Congo 처리 이후 mismatch 쌍 106개
9. ethiopia 처리 이후 mismatch 쌍 97개
10. gabon 처리 이후 mismatch 쌍 86개
11. gambia 처리 이후 mismatch 쌍 78개
12. Guinea, Kenya 처리 이후 mismatch 쌍 74개
13. lesotho 처리 이후 mismatch 쌍 66개
14. Liberia 삭제 이후 mismatch 쌍 60개
15. Malawi 처리 이후 mismatch 쌍 54개
16. Mozambique, Niger 처리 이후 mismatch 쌍 47개
17. Rwanda 처리 이후 mismatch 쌍 32개
18. Sao Tome and Principe 처리 이후 mismatch 쌍 28개
19. Senegal 처리 이후 mismatch 쌍 24개
20. Sierra Leone 처리 이후 mismatch 쌍 22개
21. south africa, togo 처리 이후 mismatch 쌍 19개
22. Uganda 처리 이후 mismatch 쌍 10개
23. United Republic of Tanzania 삭제 이후 mismatch 쌍 2개
24. zambia 처리 이후 mismatch 쌍 0개

In [ ]:
# 1. 'disease_df'의 (국가, 지역) 고유 키 셋 생성
# (이전에 만든 angola_mapping_dict 등이 이미 적용된 상태의 df 사용)
disease_keys = set(disease_df[['country', 'region_name']].itertuples(index=False, name=None))

# 2. 'standard_df'의 (국가, 지역) 고유 키 셋 생성
standard_keys = set(standard_df[['ADM0_NAME', 'ADM1_NAME']].itertuples(index=False, name=None))

# 3. 'disease_df'에만 있는 "전체 문제 목록" (Master To-Do List)
all_mismatched_pairs = disease_keys - standard_keys

print(f"앞으로 수정해야 할 (국가, 지역) 쌍이 총 {len(all_mismatched_pairs)}개 남았습니다.")

앞으로 수정해야 할 (국가, 지역) 쌍이 총 0개 남았습니다.

In [ ]:
# (국가, 지역) 튜플 리스트를 DataFrame으로 변환
mismatch_df = pd.DataFrame(list(all_mismatched_pairs), columns=['country', 'region_name'])

# 국가 이름으로 정렬
mismatch_df = mismatch_df.sort_values(by='country')

# 국가별로 어떤 지역 이름이 문제인지 확인
print("--- [전체 문제 목록 (국가별 정렬)] ---")
print(mismatch_df)

--- [전체 문제 목록 (국가별 정렬)] ---
Empty DataFrame
Columns: [country, region_name]
Index: []

In [ ]:
# 지역별 표준화 코드 생성

##**Burkina Faso**

#### **mapping pair**
- 'Boucle de Mouhoun' : 'Boucle Du Mouhoun'
- 'Centre (sans Ouagadougou)' : ?
- 'Centre-Est' : 'Centre-est'
- 'Centre-Nord' : 'Centre-nord'
- 'Centre-Ouest' : 'Centre-ouest'
- 'Centre-Sud' : 'Centre-sud'
- 'Hauts Basins' : 'Hauts-bassins'
- 'Hauts Bassins' : 'Hauts-bassins'
- 'Ouagadougou' : ?
- 'Sud-Ouest' : 'Sud-ouest'

#### **특이사항**
- Centre라는 지역을 2003년 disease 데이터에서 Centre (sans Ouagadougou), Ouagadougou로 나눠서 집계
- Ouagadougou가 주요 지역이라서 이렇게 집계한 듯
- 경기도라는 지역에 대해서 경기도, 경기도(수원시 제외), 수원시로 나누어 집계한 것과 같은 상황
- Ouagadougou의 인구(), Centre (sans Ouagadougou)의 인구()를 고려하여 하나의 Centre 발병률 행 생성해야 함

- ** Hauts Basins와 Hauts Bassins는 오타라고 판단하여 두 지역 모두 Hauts-bassins로 매핑했음**
  - 두 연도가 겹친다면 다뤄야할테지만, 두 집계는 각각 2010, 2016에 대한 집계라서 수정해줄 필요가 없음

###2006년 인구 데이터 기반 지역 내 인구 비율 계산:

- 'Ouagadougou'가 'Centre' 지역에서 차지하는 인구 비율: 1,181,702 / 1,727,390 = 약 68.4%

- 'Centre (sans Ouagadougou)'가 차지하는 인구 비율: 100% - 68.4% = 약 31.6%

### 2003년 추정치에 비율 적용:

2003년 'Centre' 지역 총 추정 인구 1,160,000명에 이 비율을 적용합니다.

####📋 2003년 최종 추정 인구
- 'Ouagadougou' (2003년 추정 인구): 1,160,000명 * 68.4% = 약 793,440명

- 'Centre (sans Ouagadougou)' (2003년 추정 인구): 1,160,000명 * 31.6% = 약 366,560명

- 가중 평균(Weighted Average)을 계산하실 때, Ouagadougou에는 약 79.3만 명, Centre (sans Ouagadougou)에는 약 36.7만 명의 인구 가중치를 적용하시면 됩니다.

In [ ]:
# 1. 정의: 상수 및 인구 정보 설정
COUNTRY = 'Burkina Faso'
YEAR = 2003
REGION_A = 'Ouagadougou'
REGION_B = 'Centre (sans Ouagadougou)'
NEW_REGION = 'Centre'

# 2003년 추정 인구 (이전 대화 기반)
POP_A = 793440  # Ouagadougou 2003 pop
POP_B = 366560  # Centre (sans...) 2003 pop
TOTAL_POP = POP_A + POP_B

# (주의) 이 코드는 disease_df가 메모리에 로드되어 있다고 가정합니다.
try:
    # 2. 데이터 추출: 2003년 Burkina Faso의 두 지역 데이터 필터링
    row_A = disease_df[
        (disease_df['country'] == COUNTRY) &
        (disease_df['year'] == YEAR) &
        (disease_df['region_name'] == REGION_A)
    ]
    row_B = disease_df[
        (disease_df['country'] == COUNTRY) &
        (disease_df['year'] == YEAR) &
        (disease_df['region_name'] == REGION_B)
    ]

    # 3. 유효성 검사: 2003년에 두 지역의 데이터가 모두 존재하는지 확인
    if row_A.empty or row_B.empty:
        print(f"오류: {YEAR}년 {COUNTRY}의 '{REGION_A}' 또는 '{REGION_B}' 데이터가 없습니다.")
        print("가중 평균을 계산할 수 없습니다.")
    else:
        # 4. 가중 평균 계산 (이미지의 'infection_rate' 컬럼 사용)
        rate_A = row_A['infection_rate'].iloc[0]
        rate_B = row_B['infection_rate'].iloc[0]

        # 분자: (비율 * 인구)의 합 = 총 발병 건수
        total_cases = (rate_A * POP_A) + (rate_B * POP_B)

        # 새로운 가중 평균 비율 계산
        new_weighted_rate = total_cases / TOTAL_POP

        # 5. 새로운 'Centre' 행 생성 (4개 주요 컬럼만)
        new_row = {
            'country': COUNTRY,
            'year': YEAR,
            'region_name': NEW_REGION,
            'infection_rate': new_weighted_rate
        }
        # (만약 4개 외 다른 컬럼이 있다면, disease_df.columns를 기반으로
        #  new_row를 채우는 더 복잡한 로직이 필요하지만,
        #  일반적으로는 주요 값만 채우고 나머지는 NaN으로 두어도 됩니다.)
        new_row_df = pd.DataFrame([new_row])

        # 6. 기존의 비표준 행(A, B) 삭제
        indices_to_drop = row_A.index.union(row_B.index)
        disease_df_cleaned = disease_df.drop(indices_to_drop)

        # 7. 새로운 'Centre' 행 추가 (원본 DataFrame에 다시 할당)
        # (중요) 이 줄은 disease_df 변수 자체를 업데이트합니다.
        disease_df = pd.concat([disease_df_cleaned, new_row_df], ignore_index=True)

        # 8. 결과 보고
        print(f"--- 작업 완료 (Year {YEAR}, {COUNTRY}) ---")
        print(f"'{REGION_A}' (Rate: {rate_A}) 및 '{REGION_B}' (Rate: {rate_B}) 행이 삭제되었습니다.")
        print(f"새로운 '{NEW_REGION}' 행이 가중 평균 Rate ({new_weighted_rate:.6f})로 생성되었습니다.")

        # (검증) 해당 연도/국가의 최종 데이터 출력
        print("\n--- 검증: 2003년 Burkina Faso 데이터 ---")
        print(disease_df[
            (disease_df['country'] == COUNTRY) &
            (disease_df['year'] == YEAR)
        ])

except NameError:
    print("오류: 'disease_df' DataFrame이 메모리에 정의되지 않았습니다.")
    print("이 코드를 실행하기 전에 disease_df를 로드해야 합니다.")
except KeyError:
    print("오류: 'infection_rate' 컬럼을 찾을 수 없습니다. 컬럼 이름을 확인하세요.")
except Exception as e:
    print(f"예상치 못한 오류 발생: {e}")

--- 작업 완료 (Year 2003, Burkina Faso) ---
'Ouagadougou' (Rate: 3.321033210332104) 및 'Centre (sans Ouagadougou)' (Rate: 0.819672131147541) 행이 삭제되었습니다.
새로운 'Centre' 행이 가중 평균 Rate (2.530603)로 생성되었습니다.

--- 검증: 2003년 Burkina Faso 데이터 ---
     year       country        region_name  infection_rate
13   2003  Burkina Faso  Boucle de Mouhoun        1.837672
14   2003  Burkina Faso           Cascades        2.359882
15   2003  Burkina Faso         Centre-Est        1.155116
16   2003  Burkina Faso        Centre-Nord        0.955414
17   2003  Burkina Faso       Centre-Ouest        2.420242
18   2003  Burkina Faso         Centre-Sud        0.857633
19   2003  Burkina Faso                Est        1.310861
20   2003  Burkina Faso      Hauts Bassins        2.145923
21   2003  Burkina Faso               Nord        1.174497
22   2003  Burkina Faso    Plateau Central        0.932091
23   2003  Burkina Faso              Sahel        0.173913
24   2003  Burkina Faso          Sud-Ouest        3.116531
681  2003  Burkina Faso             Centre        2.530603

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=='Burkina Faso']['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=='Burkina Faso']['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=='Burkina Faso']['region_name'])))

# 'Boucle de Mouhoun' : 'Boucle Du Mouhoun'
# 'Centre (sans Ouagadougou)' : ?
# 'Centre-Est' : 'Centre-est'
# 'Centre-Nord' : 'Centre-nord'
# 'Centre-Ouest' : 'Centre-ouest'
# 'Centre-Sud' : 'Centre-sud'
# 'Hauts Basins' : 'Hauts-bassins'
# 'Hauts Bassins' : 'Hauts-bassins'
# 'Ouagadougou' : ?
# 'Sud-Ouest' : 'Sud-ouest'



# 딕셔너리 만들기
burkina_mapping_dict = {
    'Boucle de Mouhoun' : 'Boucle Du Mouhoun',
    'Centre-Est' : 'Centre-est',
    'Centre-Nord' : 'Centre-nord',
    'Centre-Ouest' : 'Centre-ouest',
    'Centre-Sud' : 'Centre-sud',
    'Hauts Basins' : 'Hauts-bassins',
    'Hauts Bassins' : 'Hauts-bassins',
    'Sud-Ouest' : 'Sud-ouest'
}

disease_df.loc[disease_df['country'] == 'Burkina Faso', 'region_name'] = disease_df.loc[disease_df['country'] == 'Burkina Faso', 'region_name'].replace(burkina_mapping_dict)

print("disease data after mapping")
new_burkina_df = disease_df[disease_df['country']=='Burkina Faso']
print(new_burkina_df)

set(new_burkina_df['region_name']) - set(standard_df[standard_df['ADM0_NAME']=='Burkina Faso']['ADM1_NAME'])

disease region name
['Boucle de Mouhoun', 'Cascades', 'Centre', 'Centre-Est', 'Centre-Nord', 'Centre-Ouest', 'Centre-Sud', 'Est', 'Hauts Basins', 'Hauts Bassins', 'Nord', 'Plateau Central', 'Sahel', 'Sud-Ouest']

standard region name
['Boucle Du Mouhoun', 'Cascades', 'Centre', 'Centre-est', 'Centre-nord', 'Centre-ouest', 'Centre-sud', 'Est', 'Hauts-bassins', 'Nord', 'Plateau Central', 'Sahel', 'Sud-ouest']



mismatch list
['Boucle de Mouhoun', 'Centre (sans Ouagadougou)', 'Centre-Est', 'Centre-Nord', 'Centre-Ouest', 'Centre-Sud', 'Hauts Basins', 'Hauts Bassins', 'Ouagadougou', 'Sud-Ouest']
disease data after mapping
     year       country        region_name  infection_rate
0    2010  Burkina Faso  Boucle Du Mouhoun        0.585652
1    2010  Burkina Faso           Cascades        0.979432
2    2010  Burkina Faso             Centre        1.955671
3    2010  Burkina Faso         Centre-est        1.037736
4    2010  Burkina Faso        Centre-nord        0.379147
5    2010  Burkina Faso       Centre-ouest        1.622419
6    2010  Burkina Faso         Centre-sud        0.926784
7    2010  Burkina Faso                Est        0.957702
8    2010  Burkina Faso      Hauts-bassins        1.631543
9    2010  Burkina Faso               Nord        0.875657
10   2010  Burkina Faso    Plateau Central        0.351494
11   2010  Burkina Faso              Sahel        0.471254
12   2010  Burkina Faso          Sud-ouest        1.401051
13   2003  Burkina Faso  Boucle Du Mouhoun        1.837672
14   2003  Burkina Faso           Cascades        2.359882
15   2003  Burkina Faso         Centre-est        1.155116
16   2003  Burkina Faso        Centre-nord        0.955414
17   2003  Burkina Faso       Centre-ouest        2.420242
18   2003  Burkina Faso         Centre-sud        0.857633
19   2003  Burkina Faso                Est        1.310861
20   2003  Burkina Faso      Hauts-bassins        2.145923
21   2003  Burkina Faso               Nord        1.174497
22   2003  Burkina Faso    Plateau Central        0.932091
23   2003  Burkina Faso              Sahel        0.173913
24   2003  Burkina Faso          Sud-ouest        3.116531
681  2003  Burkina Faso             Centre        2.530603

set()

In [ ]:
disease_df[disease_df['country']=='Burkina Faso']

     year       country        region_name  infection_rate
0    2010  Burkina Faso  Boucle de Mouhoun        0.585652
1    2010  Burkina Faso           Cascades        0.979432
2    2010  Burkina Faso             Centre        1.955671
3    2010  Burkina Faso         Centre-Est        1.037736
4    2010  Burkina Faso        Centre-Nord        0.379147
5    2010  Burkina Faso       Centre-Ouest        1.622419
6    2010  Burkina Faso         Centre-Sud        0.926784
7    2010  Burkina Faso                Est        0.957702
8    2010  Burkina Faso       Hauts Basins        1.631543
9    2010  Burkina Faso               Nord        0.875657
10   2010  Burkina Faso    Plateau Central        0.351494
11   2010  Burkina Faso              Sahel        0.471254
12   2010  Burkina Faso          Sud-Ouest        1.401051
13   2003  Burkina Faso  Boucle de Mouhoun        1.837672
14   2003  Burkina Faso           Cascades        2.359882
15   2003  Burkina Faso         Centre-Est        1.155116
16   2003  Burkina Faso        Centre-Nord        0.955414
17   2003  Burkina Faso       Centre-Ouest        2.420242
18   2003  Burkina Faso         Centre-Sud        0.857633
19   2003  Burkina Faso                Est        1.310861
20   2003  Burkina Faso      Hauts Bassins        2.145923
21   2003  Burkina Faso               Nord        1.174497
22   2003  Burkina Faso    Plateau Central        0.932091
23   2003  Burkina Faso              Sahel        0.173913
24   2003  Burkina Faso          Sud-Ouest        3.116531
681  2003  Burkina Faso             Centre        2.530603

##**Burundi**

#### **mapping pair**
- 'Karusi' : 'Karuzi'

#### **특이사항**
- Bujumbura는 disease와 standard에 모두 Bujumbura_mairie, Bufumbura_rural이라는 집계 지역이 존재해서 삭제
- Centre-East, North, South, West 모두 지역이 아닌 통합지역 표현인 것 같아서 삭제
- 질병 데이터에 존재하는 지역 Rumonge는 2015년에 신설된 지역인데 standard에 없어서 문제
  - Rumonge는 2015년에 Bururi 주와 Bujumbura Rural 주의 일부가 합쳐져 생성
  - standard 데이터가 2013-2014 즈음에 생성된 shapefile같음
  - 더 최신 shp을 찾아봤으나 안 보임(조금 찾아보고 말긴 함..)
  - 다른 모든 데이터들을 standard에 맞출 예정이니 disease의 rumonge를 남겨둬도 해당 행은 아무런 값을 갖지 못함
  - standard에 왜곡 없이 맞추려면 disease의 rumonge 값을 Bururi와 Bujumbura rural에 적절히 분배해야 됨
  - 왜곡 문제가 조금 있어서 가장 간단하게 처리하는 건 bururi, bujumbura rural, rumonge 지역 집계를 모두 없애버리는 것
  - 만약 이 세 개 지역에 대한 데이터가 정말 필요한 경우, 기계학습 데이터 방법론들을 적용해서 보완해보는 것도 좋을 듯..
  => rumonge, bururi, bufumbura rural 모두 삭제했음

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=='Burundi']['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=='Burundi']['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=='Burundi']['region_name'])))

#'Bujumbura' : 없애기
#'Centre-East' : 없애기
#'Karusi' : 'Karuzi'
#'North' : 없애기
#'Rumonge': 없애기
#'South' : 없애기
#'West' : 없애기

non_standard_regions = ['Bujumbura', 'Centre-East','North','Rumonge','South','West']
disease_df = disease_df[~disease_df['region_name'].isin(non_standard_regions)]

# 딕셔너리 만들기
burundi_mapping_dict = {
    'Karusi' : 'Karuzi'
}

disease_df.loc[disease_df['country'] == 'Burundi', 'region_name'] = disease_df.loc[disease_df['country'] == 'Burundi', 'region_name'].replace(burundi_mapping_dict)

print("disease data after mapping")
new_burundi_df = disease_df[disease_df['country']=='Burundi']
print(new_burundi_df)

set(new_burundi_df['region_name']) - set(standard_df[standard_df['ADM0_NAME']=='Burundi']['ADM1_NAME'])

disease region name
['Bubanza', 'Bujumbura', 'Bujumbura Mairie', 'Bujumbura Rural', 'Bururi', 'Cankuzo', 'Centre-East', 'Cibitoke', 'Gitega', 'Karusi', 'Kayanza', 'Kirundo', 'Makamba', 'Muramvya', 'Muyinga', 'Mwaro', 'Ngozi', 'North', 'Rumonge', 'Rutana', 'Ruyigi', 'South', 'West']

standard region name
['Bubanza', 'Bujumbura Mairie', 'Bujumbura Rural', 'Bururi', 'Cankuzo', 'Cibitoke', 'Gitega', 'Karuzi', 'Kayanza', 'Kirundo', 'Makamba', 'Muramvya', 'Muyinga', 'Mwaro', 'Ngozi', 'Rutana', 'Ruyigi']



mismatch list
['Bujumbura', 'Centre-East', 'Karusi', 'North', 'Rumonge', 'South', 'West']
disease data after mapping
     year  country       region_name  infection_rate
93   2016  Burundi           Bubanza        0.520382
94   2016  Burundi  Bujumbura Mairie        2.970297
95   2016  Burundi   Bujumbura Rural        0.733496
96   2016  Burundi            Bururi        0.475285
97   2016  Burundi           Cankuzo        0.353045
98   2016  Burundi          Cibitoke        0.644122
99   2016  Burundi            Gitega        1.893939
100  2016  Burundi            Karuzi        0.493421
101  2016  Burundi           Kayanza        0.759878
102  2016  Burundi           Kirundo        1.435045
103  2016  Burundi           Makamba        0.332779
104  2016  Burundi          Muramvya        0.359066
105  2016  Burundi           Muyinga        0.372024
106  2016  Burundi             Mwaro        1.044634
107  2016  Burundi             Ngozi        0.303490
109  2016  Burundi            Rutana        0.336417
110  2016  Burundi            Ruyigi        0.344531

set()

In [ ]:
disease_df[disease_df['country']=='Burundi']

     year  country       region_name  infection_rate
93   2016  Burundi           Bubanza        0.520382
94   2016  Burundi  Bujumbura Mairie        2.970297
95   2016  Burundi   Bujumbura Rural        0.733496
96   2016  Burundi            Bururi        0.475285
97   2016  Burundi           Cankuzo        0.353045
98   2016  Burundi          Cibitoke        0.644122
99   2016  Burundi            Gitega        1.893939
100  2016  Burundi            Karusi        0.493421
101  2016  Burundi           Kayanza        0.759878
102  2016  Burundi           Kirundo        1.435045
103  2016  Burundi           Makamba        0.332779
104  2016  Burundi          Muramvya        0.359066
105  2016  Burundi           Muyinga        0.372024
106  2016  Burundi             Mwaro        1.044634
107  2016  Burundi             Ngozi        0.303490
108  2016  Burundi           Rumonge        0.849618
109  2016  Burundi            Rutana        0.336417
110  2016  Burundi            Ruyigi        0.344531
111  2010  Burundi         Bujumbura        3.686983
112  2010  Burundi       Centre-East        1.798561
113  2010  Burundi             North        1.913876
114  2010  Burundi             South        1.182519
115  2010  Burundi              West        1.344657

##**Cameroon**

#### **mapping pair**
- 'Adamawa' : 'Adamaoua'
- 'East' : 'Est'
- 'Extreme Nord' : 'Extrême - Nord'
- 'Extrême-Nord' : 'Extrême - Nord'
- 'Far-North' : 'Extrême - Nord'
- 'Nord Ouest' : 'Nord - Ouest'
- 'Nord-Ouest' : 'Nord - Ouest'
- 'North-West' : 'Nord - Ouest'
- 'South-West' : 'Sud - Ouest'
- 'Sud Ouest' : 'Sud - Ouest'
- 'Sud-Ouest' : 'Sud - Ouest'

#### **특이사항**
- 'Centre (without Yaounde)|Centre (sans Yaoundé)' : Yaounde와 합치기
- 'Douala' : Littoral과 합치기
- 'Littoral (without Douala)' : Douala와 합치기
- 'Yaounde' : Centre와 합치기
- 'Yaoundé' : Centre와 합치기
- Centre와 Littoral에 대해서 내부 지역인 Yaounde, Douala가 개별집계된 상황
  - 하나의 Centre, Littoral로 합치기
  - 2004,2011년도와 2018년도의 레이블이 다른데, 2018년도 레이블을 기준으로 합계할 예정
    - 2004,2011년 데이터 레이블 : Centre, Yaounde, Littoral, Douala
    - 2018년 데이터 레이블 : Centre(without Yaounde), Yaounde, Littoral(without Douala), Douala

- ** 2018년 데이터 Nord, Ouest, Sud가 결측치.. **

In [ ]:
# 1. 연도별 인구 딕셔너리 정의
population_data = {
    2004: {
        'Yaounde': 1817524,
        'Centre(without Yaounde)': 1280520,
        'Douala': 1907479,
        'Littoral(without Douala)': 602784
    },
    2011: {
        'Yaounde': 2440400,
        'Centre(without Yaounde)': 1479400,
        'Douala': 2447100,
        'Littoral(without Douala)': 727800
    },
    2018: {
        'Yaounde': 3672800,
        'Centre(without Yaounde)': 1451000,
        'Douala': 3539200,
        'Littoral(without Douala)': 618900
    }
}

# 1. 연도별 딕셔너리를 하나의 '마스터 딕셔너리'로 묶습니다.
#    (Key: 연도, Value: 해당 연도의 매핑 딕셔너리)
master_mapping = {
    2004: {
        'Centre': 'Centre(without Yaounde)',
        'Littoral': 'Littoral(without Douala)'
    },
    2011: {
        'Centre': 'Centre(without Yaounde)',
        'Littoral': 'Littoral(without Douala)',
        'Yaoundé' : 'Yaounde'
    },
    2018: {
        'Centre (without Yaounde)|Centre (sans Yaoundé)' :'Centre(without Yaounde)',
        'Littoral (without Douala)' : 'Littoral(without Douala)'
    }
}

years_to_rename = [2004, 2011, 2018]

print("레이블 통일 시작...")
for year in years_to_rename:
    # 2. 현재 연도(year)에 맞는 딕셔너리를 마스터에서 꺼냅니다.
    current_mapping_dict = master_mapping[year]

    mask = (disease_df['country'] == 'Cameroon') & (disease_df['year'] == year)

    # 3. 꺼내온 'current_mapping_dict' (변수)를 replace에 적용합니다.
    disease_df.loc[mask, 'region_name'] = disease_df.loc[mask, 'region_name'].replace(current_mapping_dict)

print(f"{years_to_rename}년도 레이블 통일 완료.")


# 2. 집계할 연도 목록
years_to_process = [2004, 2011, 2018]
new_rows = [] # 합쳐진 행들을 임시 저장할 리스트

for year in years_to_process:
    print(f"\n--- {year}년 데이터 집계 시작 ---")
    pop = population_data[year]

    # --- A. Centre / Yaounde 합치기 ---
    regions_centre = ['Centre(without Yaounde)', 'Yaounde']
    df_centre_parts = disease_df[
        (disease_df['country'] == 'Cameroon') &
        (disease_df['year'] == year) &
        (disease_df['region_name'].isin(regions_centre))
    ]

    if len(df_centre_parts) == 2:
        rate_A = df_centre_parts.loc[df_centre_parts['region_name'] == 'Centre(without Yaounde)', 'infection_rate'].iloc[0]
        pop_A = pop['Centre(without Yaounde)']

        rate_B = df_centre_parts.loc[df_centre_parts['region_name'] == 'Yaounde', 'infection_rate'].iloc[0]
        pop_B = pop['Yaounde']

        # 가중 평균 계산
        total_cases = (rate_A * pop_A) + (rate_B * pop_B)
        total_pop = pop_A + pop_B
        new_rate = total_cases / total_pop

        new_rows.append({'country': 'Cameroon', 'year': year, 'region_name': 'Centre', 'infection_rate': new_rate})
        print(f"'{year} Centre' 생성 완료 (Rate: {new_rate:.6f})")
    else:
        print(f"경고: {year}년 Centre/Yaounde 데이터가 2개가 아닙니다. 건너뜁니다.")

    # --- B. Littoral / Douala 합치기 ---
    regions_littoral = ['Littoral(without Douala)', 'Douala']
    df_littoral_parts = disease_df[
        (disease_df['country'] == 'Cameroon') &
        (disease_df['year'] == year) &
        (disease_df['region_name'].isin(regions_littoral))
    ]

    if len(df_littoral_parts) == 2:
        rate_A = df_littoral_parts.loc[df_littoral_parts['region_name'] == 'Littoral(without Douala)', 'infection_rate'].iloc[0]
        pop_A = pop['Littoral(without Douala)']

        rate_B = df_littoral_parts.loc[df_littoral_parts['region_name'] == 'Douala', 'infection_rate'].iloc[0]
        pop_B = pop['Douala']

        # 가중 평균 계산
        total_cases = (rate_A * pop_A) + (rate_B * pop_B)
        total_pop = pop_A + pop_B
        new_rate = total_cases / total_pop

        new_rows.append({'country': 'Cameroon', 'year': year, 'region_name': 'Littoral', 'infection_rate': new_rate})
        print(f"'{year} Littoral' 생성 완료 (Rate: {new_rate:.6f})")
    else:
        print(f"경고: {year}년 Littoral/Douala 데이터가 2개가 아닙니다. 건너뜁니다.")


# 3. 기존의 비표준 행들 모두 삭제
regions_to_delete = [
    'Centre(without Yaounde)', 'Yaounde',
    'Littoral(without Douala)', 'Douala'
]
disease_df = disease_df[
    ~( (disease_df['country'] == 'Cameroon') &
       (disease_df['region_name'].isin(regions_to_delete)) )
]

# 4. 새로 생성된 'Centre', 'Littoral' 행들을 원본에 추가
if new_rows:
    disease_df = pd.concat([disease_df, pd.DataFrame(new_rows)], ignore_index=True)

print("\n--- [최종 작업 완료] ---")
print("카메룬 데이터 집계가 완료되었습니다.")
print(disease_df[disease_df['country'] == 'Cameroon'].sort_values(by='year'))

레이블 통일 시작...
[2004, 2011, 2018]년도 레이블 통일 완료.

--- 2004년 데이터 집계 시작 ---
'2004 Centre' 생성 완료 (Rate: 6.508009)
'2004 Littoral' 생성 완료 (Rate: 4.792967)

--- 2011년 데이터 집계 시작 ---
'2011 Centre' 생성 완료 (Rate: 5.751725)
'2011 Littoral' 생성 완료 (Rate: 4.412564)

--- 2018년 데이터 집계 시작 ---
'2018 Centre' 생성 완료 (Rate: 3.053378)
'2018 Littoral' 생성 완료 (Rate: 2.203487)

--- [최종 작업 완료] ---
카메룬 데이터 집계가 완료되었습니다.
     year   country   region_name  infection_rate
84   2004  Cameroon     Sud Ouest        7.647059
83   2004  Cameroon           Sud        5.882353
82   2004  Cameroon         Ouest        4.214963
81   2004  Cameroon    Nord Ouest        8.101852
80   2004  Cameroon          Nord        1.594533
79   2004  Cameroon  Extreme Nord        1.773836
78   2004  Cameroon           Est        8.108108
77   2004  Cameroon      Adamaoua        6.857855
652  2004  Cameroon        Centre        6.508009
653  2004  Cameroon      Littoral        4.792967
76   2011  Cameroon     Sud-Ouest        5.641026
75   2011  Cameroon           Sud        6.659506
72   2011  Cameroon          Nord        2.452830
71   2011  Cameroon  Extrême-Nord        1.274313
74   2011  Cameroon         Ouest        2.820306
73   2011  Cameroon    Nord-Ouest        6.317301
69   2011  Cameroon      Adamaoua        5.000000
70   2011  Cameroon           Est        6.378601
654  2011  Cameroon        Centre        5.751725
655  2011  Cameroon      Littoral        4.412564
137  2018  Cameroon    North-West        4.117647
136  2018  Cameroon     Far-North        1.040944
135  2018  Cameroon          East        5.355715
134  2018  Cameroon       Adamawa        3.608247
138  2018  Cameroon    South-West        3.324100
656  2018  Cameroon        Centre        3.053378
657  2018  Cameroon      Littoral        2.203487

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=='Cameroon']['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=='Cameroon']['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=='Cameroon']['region_name'])))


# 딕셔너리 만들기
cameroon_mapping_dict = {
    'Adamawa' : 'Adamaoua',
    'East' : 'Est',
    'Extreme Nord' : 'Extrême - Nord',
    'Extrême-Nord' : 'Extrême - Nord',
    'Far-North' : 'Extrême - Nord',
    'Nord Ouest' : 'Nord - Ouest',
    'Nord-Ouest' : 'Nord - Ouest',
    'North-West' : 'Nord - Ouest',
    'South-West' : 'Sud - Ouest',
    'Sud Ouest' : 'Sud - Ouest',
    'Sud-Ouest' : 'Sud - Ouest'
}

disease_df.loc[disease_df['country'] == 'Cameroon', 'region_name'] = disease_df.loc[disease_df['country'] == 'Cameroon', 'region_name'].replace(cameroon_mapping_dict)

print("disease data after mapping")
new_cameroon_df = disease_df[disease_df['country']=='Cameroon']
print(new_cameroon_df)

set(new_cameroon_df['region_name']) - set(standard_df[standard_df['ADM0_NAME']=='Cameroon']['ADM1_NAME'])

disease region name
['Adamaoua', 'Adamawa', 'Centre', 'East', 'Est', 'Extreme Nord', 'Extrême-Nord', 'Far-North', 'Littoral', 'Nord', 'Nord Ouest', 'Nord-Ouest', 'North-West', 'Ouest', 'South-West', 'Sud', 'Sud Ouest', 'Sud-Ouest']

standard region name
['Adamaoua', 'Centre', 'Est', 'Extrême - Nord', 'Littoral', 'Nord', 'Nord - Ouest', 'Ouest', 'Sud', 'Sud - Ouest']



mismatch list
['Adamawa', 'East', 'Extreme Nord', 'Extrême-Nord', 'Far-North', 'Nord Ouest', 'Nord-Ouest', 'North-West', 'South-West', 'Sud Ouest', 'Sud-Ouest']
disease data after mapping
     year   country     region_name  infection_rate
69   2011  Cameroon        Adamaoua        5.000000
70   2011  Cameroon             Est        6.378601
71   2011  Cameroon  Extrême - Nord        1.274313
72   2011  Cameroon            Nord        2.452830
73   2011  Cameroon    Nord - Ouest        6.317301
74   2011  Cameroon           Ouest        2.820306
75   2011  Cameroon             Sud        6.659506
76   2011  Cameroon     Sud - Ouest        5.641026
77   2004  Cameroon        Adamaoua        6.857855
78   2004  Cameroon             Est        8.108108
79   2004  Cameroon  Extrême - Nord        1.773836
80   2004  Cameroon            Nord        1.594533
81   2004  Cameroon    Nord - Ouest        8.101852
82   2004  Cameroon           Ouest        4.214963
83   2004  Cameroon             Sud        5.882353
84   2004  Cameroon     Sud - Ouest        7.647059
134  2018  Cameroon        Adamaoua        3.608247
135  2018  Cameroon             Est        5.355715
136  2018  Cameroon  Extrême - Nord        1.040944
137  2018  Cameroon    Nord - Ouest        4.117647
138  2018  Cameroon     Sud - Ouest        3.324100
652  2004  Cameroon          Centre        6.508009
653  2004  Cameroon        Littoral        4.792967
654  2011  Cameroon          Centre        5.751725
655  2011  Cameroon        Littoral        4.412564
656  2018  Cameroon          Centre        3.053378
657  2018  Cameroon        Littoral        2.203487

set()

In [ ]:
disease_df[disease_df['country']=='Cameroon']

,year,country,region_name,infection_rate
71,2011,Cameroon,Adamaoua,5.000000
72,2011,Cameroon,Centre,5.630452
73,2011,Cameroon,Douala,4.524887
74,2011,Cameroon,Est,6.378601
75,2011,Cameroon,Extrême-Nord,1.274313
76,2011,Cameroon,Littoral,4.034896
77,2011,Cameroon,Nord,2.452830
78,2011,Cameroon,Nord-Ouest,6.317301
79,2011,Cameroon,Ouest,2.820306
80,2011,Cameroon,Sud,6.659506
81,2011,Cameroon,Sud-Ouest,5.641026
82,2011,Cameroon,Yaoundé,5.825243
83,2004,Cameroon,Adamaoua,6.857855
84,2004,Cameroon,Centre,4.111111
85,2004,Cameroon,Douala,4.545455
86,2004,Cameroon,Est,8.108108
87,2004,Cameroon,Extreme Nord,1.773836
88,2004,Cameroon,Littoral,5.576208
89,2004,Cameroon,Nord,1.594533
90,2004,Cameroon,Nord Ouest,8.101852
91,2004,Cameroon,Ouest,4.214963
92,2004,Cameroon,Sud,5.882353
93,2004,Cameroon,Sud Ouest,7.647059
94,2004,Cameroon,Yaounde,8.196721
150,2018,Cameroon,Adamawa,3.608247
151,2018,Cameroon,Centre (without Yaounde)|Centre (sans Yaoundé),3.815490
152,2018,Cameroon,Douala,2.125920
153,2018,Cameroon,East,5.355715
154,2018,Cameroon,Far-North,1.040944
155,2018,Cameroon,Littoral (without Douala),2.647059
157,2018,Cameroon,North-West,4.117647
159,2018,Cameroon,South-West,3.324100
161,2018,Cameroon,Yaounde,2.752294

In [ ]:
until_cameroon_df = disease_df

##**Chad**

#### **mapping pair**
- 'Barh El Gazal': 'Barl El Gazal',
- 'Guéra': 'Guera',
- 'Hadjer-Lamis': 'Hadjer Lamis',
- 'Ouaddaï': 'Ouaddai',
- 'Wadi Fira': 'Biltine'

#### **특이사항**
- standard 데이터가 Level1, Level2 지역명 그리고 옛 이름까지 섞여있어 삭제가 필요함
- 'Batha': # (1:N 문제) standard는 'Batha Est', 'Batha Ouest'로 2개임
- 'Borkou/Tibesti': (N:1 문제) standard는 'Borkou', 'Tibesti'로 2개임
- 'Chari Baguirmi': (L1:L2 문제) standard는 하위 L2(Baguirmi)만 포함
- 'Mayo Kebbi Est': (L1:L2 문제) standard는 하위 L2들만 포함
- 'Mayo Kebbi Ouest': (L1:L2 문제) standard는 하위 L2들만 포함
- 'Moyen Chari': (L1:L2 문제) standard는 하위 L2들만 포함
- "N'Djaména": (수도 누락) standard 인덱스에 수도가 없음
- 'Tandjilé': (1:N 문제) standard는 'Tandjile Est', 'Tandjile Ouest'로 2개임

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=='Chad']['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=='Chad']['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=='Chad']['region_name'])))

disease region name
['Barh El Gazal', 'Batha', 'Borkou/Tibesti', 'Chari Baguirmi', 'Ennedi', 'Guéra', 'Hadjer-Lamis', 'Kanem', 'Lac', 'Logone Occidental', 'Logone Oriental', 'Mandoul', 'Mayo Kebbi Est', 'Mayo Kebbi Ouest', 'Moyen Chari', "N'Djaména", 'Ouaddaï', 'Salamat', 'Sila', 'Tandjilé', 'Wadi Fira']

standard region name
['Assongha', 'Baguirmi', 'Barh Koh', 'Barl El Gazal', 'Batha Est', 'Batha Ouest', 'Biltine', 'Borkou', 'Daraba', 'Ennedi', 'Guera', 'Hadjer Lamis', 'Kabia', 'Kanem', 'Lac', 'Lac Iro', 'Logone Occidental', 'Logone Oriental', 'Mandoul', 'Mayo-Boneye', 'Mayo-Dala', 'Mont De Lam', 'Ouaddai', 'Salamat', 'Sila', 'Tandjile Est', 'Tandjile Ouest', 'Tibesti']



mismatch list
['Barh El Gazal', 'Batha', 'Borkou/Tibesti', 'Chari Baguirmi', 'Guéra', 'Hadjer-Lamis', 'Mayo Kebbi Est', 'Mayo Kebbi Ouest', 'Moyen Chari', "N'Djaména", 'Ouaddaï', 'Tandjilé', 'Wadi Fira']

In [ ]:
#매핑할 차드(Chad) 지역 딕셔너리
mapping_dict_chad = {
    # 오타 (l vs h)
    'Barh El Gazal': 'Barl El Gazal',

    # 악센트 제거
    'Guéra': 'Guera',

    # 하이픈 제거
    'Hadjer-Lamis': 'Hadjer Lamis',

    # 악센트 제거
    'Ouaddaï': 'Ouaddai',

    # 역사적 이름 변경 (Wadi Fira(신) -> Biltine(구))
    'Wadi Fira': 'Biltine'
}

# 삭제할 차드(Chad) 지역 목록
regions_to_delete_chad = [
    # (1:N 문제) standard는 'Batha Est', 'Batha Ouest'로 2개임
    'Batha',

    # (N:1 문제) standard는 'Borkou', 'Tibesti'로 2개임
    'Borkou/Tibesti',

    # (L1:L2 문제) standard는 하위 L2(Baguirmi)만 포함
    'Chari Baguirmi',

    # (L1:L2 문제) standard는 하위 L2들만 포함
    'Mayo Kebbi Est',
    'Mayo Kebbi Ouest',
    'Moyen Chari',

    # (수도 누락) standard 인덱스에 수도가 없음
    "N'Djaména",

    # (1:N 문제) standard는 'Tandjile Est', 'Tandjile Ouest'로 2개임
    'Tandjilé'
]

In [ ]:
print(f"--- 차드(Chad) 데이터 정리 시작 ---")

try:
    # (검증) 원본 데이터 행 수
    original_count = len(disease_df[disease_df['country'] == 'Chad'])
    print(f"원본 'Chad' 행 개수: {original_count}")

    # 3-1. 1단계: 매핑 불가능한 행 우선 삭제

    # 삭제할 행의 인덱스를 찾습니다.
    indices_to_drop = disease_df[
        (disease_df['country'] == 'Chad') &
        (disease_df['region_name'].isin(regions_to_delete_chad))
    ].index

    # 원본(disease_df)에서 해당 인덱스를 삭제합니다.
    disease_df_cleaned = disease_df.drop(indices_to_drop)

    print(f"1단계: 매핑 불가 지역 {len(indices_to_drop)}개 행 삭제 완료.")

    # 3-2. 2단계: 오타 및 역사적 이름 매핑

    # (중요) 'Chad' 국가에만 .loc[]를 사용해 안전하게 적용합니다.
    mask = (disease_df_cleaned['country'] == 'Chad')
    disease_df_cleaned.loc[mask, 'region_name'] = disease_df_cleaned.loc[mask, 'region_name'].replace(mapping_dict_chad)

    print("2단계: 오타 및 역사적 이름 매핑 완료.")

    # 3-3. (중요) 원본 DataFrame 변수 덮어쓰기
    disease_df = disease_df_cleaned

    print(f"최종 'Chad' 행 개수: {len(disease_df[disease_df['country'] == 'Chad'])}")
    print("--- 차드(Chad) 데이터 정리 완료 ---")

except NameError:
    print("오류: 'disease_df'가 메모리에 없습니다. 먼저 로드해주세요.")
except Exception as e:
    print(f"예상치 못한 오류 발생: {e}")

--- 차드(Chad) 데이터 정리 시작 ---
원본 'Chad' 행 개수: 21
1단계: 매핑 불가 지역 8개 행 삭제 완료.
2단계: 오타 및 역사적 이름 매핑 완료.
최종 'Chad' 행 개수: 13
--- 차드(Chad) 데이터 정리 완료 ---

In [ ]:
print("disease data after mapping")
new_chad_df = disease_df[disease_df['country']=='Chad']
print(new_chad_df)

set(new_chad_df['region_name']) - set(standard_df[standard_df['ADM0_NAME']=='Chad']['ADM1_NAME'])

disease data after mapping
     year country        region_name  infection_rate
113  2014    Chad      Barl El Gazal        1.160542
117  2014    Chad             Ennedi        1.949861
118  2014    Chad              Guera        0.760456
119  2014    Chad       Hadjer Lamis        1.530612
120  2014    Chad              Kanem        0.349040
121  2014    Chad                Lac        3.186646
122  2014    Chad  Logone Occidental        1.598579
123  2014    Chad    Logone Oriental        0.176991
124  2014    Chad            Mandoul        1.160862
129  2014    Chad            Ouaddai        0.526316
130  2014    Chad            Salamat        0.782779
131  2014    Chad               Sila        0.000000
133  2014    Chad            Biltine        0.757576

set()

In [ ]:
disease_df[disease_df['country']=='Chad']

     year country        region_name  infection_rate
113  2014    Chad      Barh El Gazal        1.160542
114  2014    Chad              Batha        0.498753
115  2014    Chad     Borkou/Tibesti        3.643725
116  2014    Chad     Chari Baguirmi        1.663202
117  2014    Chad             Ennedi        1.949861
118  2014    Chad              Guéra        0.760456
119  2014    Chad       Hadjer-Lamis        1.530612
120  2014    Chad              Kanem        0.349040
121  2014    Chad                Lac        3.186646
122  2014    Chad  Logone Occidental        1.598579
123  2014    Chad    Logone Oriental        0.176991
124  2014    Chad            Mandoul        1.160862
125  2014    Chad     Mayo Kebbi Est        1.225919
126  2014    Chad   Mayo Kebbi Ouest        0.811688
127  2014    Chad        Moyen Chari        2.371542
128  2014    Chad          N'Djaména        3.925417
129  2014    Chad            Ouaddaï        0.526316
130  2014    Chad            Salamat        0.782779
131  2014    Chad               Sila        0.000000
132  2014    Chad           Tandjilé        2.534113
133  2014    Chad          Wadi Fira        0.757576

##**Congo**

#### **mapping pair**
- 'Bouénza' : 'Bouenza'
- 'Cuvette-Ouest' : 'Cuvette Ovest'
- 'Lékoumou' : 'Lekoumou'

#### **특이사항**
- 'Pointe-Noire' : 삭제, 경제 중심지를 의미함..
- 'Brazzaville' : 삭제, 수도를 의미함..

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=='Congo']['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=='Congo']['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=='Congo']['region_name'])))

# 'Bouénza' : 'Bouenza'
# 'Cuvette-Ouest' : 'Cuvette Ovest'
# 'Lékoumou' : 'Lekoumou'
# 'Pointe-Noire' : ?
# 'Brazzaville' : ?

non_standard_regions_congo = ['Pointe-Noire', 'Brazzaville']
indices_to_drop = disease_df[
    (disease_df['country'] == 'Congo') &
    (disease_df['region_name'].isin(non_standard_regions_congo))
].index

disease_df = disease_df.drop(indices_to_drop)

# 딕셔너리 만들기
congo_mapping_dict = {
    'Bouénza' : 'Bouenza',
    'Cuvette-Ouest' : 'Cuvette Ovest',
    'Lékoumou' : 'Lekoumou'
}

disease_df.loc[disease_df['country'] == 'Congo', 'region_name'] = disease_df.loc[disease_df['country'] == 'Congo', 'region_name'].replace(congo_mapping_dict)

print("disease data after mapping")
new_congo_df = disease_df[disease_df['country']=='Congo']
print(new_congo_df)

set(new_congo_df['region_name']) - set(standard_df[standard_df['ADM0_NAME']=='Congo']['ADM1_NAME'])

disease region name
['Bouénza', 'Brazzaville', 'Cuvette', 'Cuvette-Ouest', 'Kouilou', 'Likouala', 'Lékoumou', 'Niari', 'Plateaux', 'Pointe-Noire', 'Pool', 'Sangha']

standard region name
['Bouenza', 'Cuvette', 'Cuvette Ovest', 'Kouilou', 'Lekoumou', 'Likouala', 'Niari', 'Plateaux', 'Pool', 'Sangha']



mismatch list
['Bouénza', 'Brazzaville', 'Cuvette-Ouest', 'Lékoumou', 'Pointe-Noire']
disease data after mapping
    year country    region_name  infection_rate
57  2009   Congo        Bouenza        3.937729
59  2009   Congo        Cuvette        2.011494
60  2009   Congo  Cuvette Ovest        1.438849
61  2009   Congo        Kouilou        3.611738
62  2009   Congo       Likouala        1.879699
63  2009   Congo       Lekoumou        2.872777
64  2009   Congo          Niari        3.959484
65  2009   Congo       Plateaux        2.845100
67  2009   Congo           Pool        1.447178
68  2009   Congo         Sangha        3.485839

set()

In [ ]:
disease_df[disease_df['country']=='Congo']

    year country    region_name  infection_rate
57  2009   Congo        Bouénza        3.937729
58  2009   Congo    Brazzaville        2.365464
59  2009   Congo        Cuvette        2.011494
60  2009   Congo  Cuvette-Ouest        1.438849
61  2009   Congo        Kouilou        3.611738
62  2009   Congo       Likouala        1.879699
63  2009   Congo       Lékoumou        2.872777
64  2009   Congo          Niari        3.959484
65  2009   Congo       Plateaux        2.845100
66  2009   Congo   Pointe-Noire        4.871060
67  2009   Congo           Pool        1.447178
68  2009   Congo         Sangha        3.485839

##**Côte d'Ivoire**

#### **특이사항**
- disease 데이터와 standard 데이터는 지역 이름이 단 하나도 일치하지 않음

- standard (마스터)는 2011년 이후의 14개 공식 행정구역(District) 이름을 사용합니다. (예: Bas Sassandra, Gôh-Djiboua, Savanes)

- disease 데이터는 2011년 이전의 비표준 또는 역사적인 10~16개 "방위" 이름을 사용합니다. (예: Nord, Sud-Ouest, Centre)

** ->결과적으로 매핑이 불가한 지역들을 삭제하고, 나머지 매핑하면 한 개의 지역만 남아서,, Côte d'Ivoire는 아예 삭제하는 게 더 나을 듯 **

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="Côte d'Ivoire"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="Côte d'Ivoire"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="Côte d'Ivoire"]['region_name'])))

disease region name
['Centre', 'Centre Nord', 'Centre-Est', 'Centre-Nord', 'Centre-Ouest', 'Nord', 'Nord-Est', 'Nord-Ouest', 'Nord-est', 'Nou=rd-Ouest', 'Ouest', 'Sud', 'Sud sans Abidjan', 'Sud-Ouest', 'Sud-ouest', "Ville d'Abidjan"]

standard region name
['Bas Sassandra', 'Comoe', 'Denguele', 'District autonome de Abidjan', 'District autonome de Yamoussoukro', 'Gôh-Djiboua', 'Lacs', 'Lagunes', 'Montagnes', 'Sassandra-Marahoue', 'Savanes', 'Vallee Du Bandama', 'Woroba', 'Zanzan']



mismatch list
['Centre', 'Centre Nord', 'Centre-Est', 'Centre-Nord', 'Centre-Ouest', 'Nord', 'Nord-Est', 'Nord-Ouest', 'Nord-est', 'Nou=rd-Ouest', 'Ouest', 'Sud', 'Sud sans Abidjan', 'Sud-Ouest', 'Sud-ouest', "Ville d'Abidjan"]

In [ ]:
disease_df[disease_df['country']=="Côte d'Ivoire"]

     year        country       region_name  infection_rate
611  2005  Côte d'Ivoire            Centre        4.659843
612  2005  Côte d'Ivoire       Centre Nord        3.616612
613  2005  Côte d'Ivoire        Centre-Est        3.733621
614  2005  Côte d'Ivoire      Centre-Ouest        3.896660
615  2005  Côte d'Ivoire              Nord        3.023113
616  2005  Côte d'Ivoire          Nord-Est        3.987058
617  2005  Côte d'Ivoire      Nou=rd-Ouest        1.915881
618  2005  Côte d'Ivoire             Ouest        4.507820
619  2005  Côte d'Ivoire               Sud        4.479435
620  2005  Côte d'Ivoire         Sud-Ouest        4.191536
621  2005  Côte d'Ivoire   Ville d'Abidjan        8.134462
622  2011  Côte d'Ivoire            Centre        3.165468
623  2011  Côte d'Ivoire        Centre-Est        3.897550
624  2011  Côte d'Ivoire       Centre-Nord        4.942166
625  2011  Côte d'Ivoire      Centre-Ouest        2.732919
626  2011  Côte d'Ivoire              Nord        2.529960
627  2011  Côte d'Ivoire        Nord-Ouest        2.252693
628  2011  Côte d'Ivoire          Nord-est        3.624161
629  2011  Côte d'Ivoire             Ouest        4.171123
630  2011  Côte d'Ivoire  Sud sans Abidjan        4.160475
631  2011  Côte d'Ivoire         Sud-ouest        3.276699
632  2011  Côte d'Ivoire   Ville d'Abidjan        5.655738

In [ ]:
print(f"삭제 전 전체 행 개수: {len(disease_df)}")

# 'country'가 "Côte d'Ivoire"가 아닌(!=) 행들만 선택하여 덮어씁니다.
disease_df = disease_df[disease_df['country'] != "Côte d'Ivoire"]

# (확인) 삭제 후 행 개수 확인
print(f"삭제 후 전체 행 개수: {len(disease_df)}")
print("Côte d'Ivoire 행 삭제 완료.")

삭제 전 전체 행 개수: 648
삭제 후 전체 행 개수: 626
Côte d'Ivoire 행 삭제 완료.

##**Democratic Republic of the Congo**

#### **mapping pair**
-

#### **특이사항**
- standard 데이터가 2015년 이후의 지역명 변경을 반영하지 못해서, 2023년도 데이터와는 심각한 불일치 발생
- 2015년 이전의 2007,2013 년도 데이터는 오타만 매핑하였고,
- 2015년 이후 데이터인 2023년도 데이터에 대해서는 과거 지역에 맞게 발병률 합산함

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="Democratic Republic of the Congo"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="Democratic Republic of the Congo"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="Democratic Republic of the Congo"]['region_name'])))


#2007, 2013년도의 오타에 대한 매핑
drc_mapping_dict = {
    'Kasaï Occident':'Kasai Occidental',
    'Kasai-Occidental':'Kasai Occidental',
    'Kasaï Oriental': 'Kasai Oriental',
    'Kasai-Oriental':'Kasai Oriental'

}

disease_df.loc[disease_df['country'] == 'Democratic Republic of the Congo', 'region_name'] = disease_df.loc[disease_df['country'] == 'Democratic Republic of the Congo', 'region_name'].replace(drc_mapping_dict)

print("disease data after mapping")
new_drc_df = disease_df[disease_df['country']=='Democratic Republic of the Congo']
print(new_drc_df)

set(new_drc_df['region_name']) - set(standard_df[standard_df['ADM0_NAME']=='Democratic Republic of the Congo']['ADM1_NAME'])

disease region name
['Bandundu', 'Bas-Congo', 'Bas-Uele', 'Equateur', 'Haut Lomami', 'Haut Uele', 'Haut-Katanga', 'Ituri', 'Kasai-Occidental', 'Kasai-Oriental', 'Kasaï', 'Kasaï Central', 'Kasaï Occident', 'Kasaï Oriental', 'Katanga', 'Kinshasa', 'Kongo Central', 'Kwango', 'Kwilu', 'Lomami', 'Lualaba', 'Mai-Ndombe', 'Maniema', 'Mongala', 'Nord Ubangi', 'Nord-Kivu', 'Orientale', 'Sankuru', 'Sud Ubangi', 'Sud-Kivu', 'Tanganyika', 'Tshopo', 'Tshuapa']

standard region name
['Bandundu', 'Bas-Congo', 'Equateur', 'Kasai Occidental', 'Kasai Oriental', 'Katanga', 'Kinshasa', 'Maniema', 'Nord-Kivu', 'Orientale', 'Sud-Kivu']



mismatch list
['Bas-Uele', 'Haut Lomami', 'Haut Uele', 'Haut-Katanga', 'Ituri', 'Kasai-Occidental', 'Kasai-Oriental', 'Kasaï', 'Kasaï Central', 'Kasaï Occident', 'Kasaï Oriental', 'Kongo Central', 'Kwango', 'Kwilu', 'Lomami', 'Lualaba', 'Mai-Ndombe', 'Mongala', 'Nord Ubangi', 'Sankuru', 'Sud Ubangi', 'Tanganyika', 'Tshopo', 'Tshuapa']
disease data after mapping
     year                           country       region_name  infection_rate
102  2007  Democratic Republic of the Congo          Bandundu        0.525210
103  2007  Democratic Republic of the Congo         Bas-Congo        1.376147
104  2007  Democratic Republic of the Congo          Equateur        1.179245
105  2007  Democratic Republic of the Congo  Kasai Occidental        0.718391
106  2007  Democratic Republic of the Congo    Kasai Oriental        1.593137
107  2007  Democratic Republic of the Congo           Katanga        1.985981
108  2007  Democratic Republic of the Congo          Kinshasa        1.876877
109  2007  Democratic Republic of the Congo           Maniema        0.462428
110  2007  Democratic Republic of the Congo         Nord-Kivu        1.335113
111  2007  Democratic Republic of the Congo         Orientale        2.264151
112  2007  Democratic Republic of the Congo          Sud-Kivu        1.966292
165  2023  Democratic Republic of the Congo          Bas-Uele        2.344828
166  2023  Democratic Republic of the Congo          Equateur        1.027077
167  2023  Democratic Republic of the Congo       Haut Lomami        1.457195
168  2023  Democratic Republic of the Congo         Haut Uele        6.089744
169  2023  Democratic Republic of the Congo      Haut-Katanga        1.795332
170  2023  Democratic Republic of the Congo             Ituri        2.345582
171  2023  Democratic Republic of the Congo             Kasaï        0.482703
172  2023  Democratic Republic of the Congo     Kasaï Central        0.469851
173  2023  Democratic Republic of the Congo    Kasai Oriental        1.107754
174  2023  Democratic Republic of the Congo          Kinshasa        0.422297
175  2023  Democratic Republic of the Congo     Kongo Central        0.844773
176  2023  Democratic Republic of the Congo            Kwango        0.000000
177  2023  Democratic Republic of the Congo             Kwilu        0.359712
178  2023  Democratic Republic of the Congo            Lomami        0.298805
179  2023  Democratic Republic of the Congo           Lualaba        1.330798
180  2023  Democratic Republic of the Congo        Mai-Ndombe        0.457666
181  2023  Democratic Republic of the Congo           Maniema        0.394477
182  2023  Democratic Republic of the Congo           Mongala        0.383509
183  2023  Democratic Republic of the Congo       Nord Ubangi        0.104167
184  2023  Democratic Republic of the Congo         Nord-Kivu        0.806452
185  2023  Democratic Republic of the Congo           Sankuru        0.396301
186  2023  Democratic Republic of the Congo        Sud Ubangi        0.754717
187  2023  Democratic Republic of the Congo          Sud-Kivu        0.503525
188  2023  Democratic Republic of the Congo        Tanganyika        0.381679
189  2023  Democratic Republic of the Congo            Tshopo        0.100402
190  2023  Democratic Republic of the Congo           Tshuapa        1.923077
600  2013  Democratic Republic of the Congo          Bandundu        0.256520
601  2013  Democratic Republic of the Congo         Bas-Congo        0.430108
602  2013  Democratic Republic of the Congo          Equateur        0.843109
603  2013  Democratic Republic of the Congo  Kasai Occidental        0.494350
604  2013  Democratic Republic of the Congo    Kasai Oriental        1.275761
605  2013  Democratic Republic of the Congo           Katanga        1.091902
606  2013  Democratic Republic of the Congo          Kinshasa        1.523810
607  2013  Democratic Republic of the Congo           Maniema        1.799775
608  2013  Democratic Republic of the Congo         Nord-Kivu        0.931099
609  2013  Democratic Republic of the Congo         Orientale        1.819923
610  2013  Democratic Republic of the Congo          Sud-Kivu        0.509165

{'Bas-Uele',
 'Haut Lomami',
 'Haut Uele',
 'Haut-Katanga',
 'Ituri',
 'Kasaï',
 'Kasaï Central',
 'Kongo Central',
 'Kwango',
 'Kwilu',
 'Lomami',
 'Lualaba',
 'Mai-Ndombe',
 'Mongala',
 'Nord Ubangi',
 'Sankuru',
 'Sud Ubangi',
 'Tanganyika',
 'Tshopo',
 'Tshuapa'}

In [ ]:
#백업
until_drc_2013_df = disease_df

In [ ]:
disease_df = until_drc_2013_df
disease_df

     year       country        region_name  infection_rate
0    2010  Burkina Faso  Boucle Du Mouhoun        0.585652
1    2010  Burkina Faso           Cascades        0.979432
2    2010  Burkina Faso             Centre        1.955671
3    2010  Burkina Faso         Centre-est        1.037736
4    2010  Burkina Faso        Centre-nord        0.379147
..    ...           ...                ...             ...
653  2004      Cameroon           Littoral        4.792967
654  2011      Cameroon             Centre        5.751725
655  2011      Cameroon           Littoral        4.412564
656  2018      Cameroon             Centre        3.053378
657  2018      Cameroon           Littoral        2.203487

[626 rows x 4 columns]

In [ ]:

# --- 1. 설정 ---
COUNTRY_NAME = 'Democratic Republic of the Congo'

print(f"--- [DRC] {COUNTRY_NAME} 시공간 롤백(Roll-back) 작업 시작 ---")

try:
    # --- 2. 롤백 매핑: "새 주(Key)" -> "옛 주(Value)" ---
    # (2023년 목록을 standard 목록(Katanga, Bandundu 등)으로 매핑)
    rollback_mapping_drc = {
        # Katanga (standard) -> 4 new
        'Haut-Katanga': 'Katanga',
        'Haut Lomami': 'Katanga',
        'Lualaba': 'Katanga',
        'Tanganyika': 'Katanga',

        # Bandundu (standard) -> 3 new
        'Kwango': 'Bandundu',
        'Kwilu': 'Bandundu',
        'Mai-Ndombe': 'Bandundu',

        # Orientale (standard) -> 4 new
        'Bas-Uele': 'Orientale',
        'Haut Uele': 'Orientale',
        'Ituri': 'Orientale',
        'Tshopo': 'Orientale',

        # Equateur (standard) -> 5 new
        'Equateur': 'Equateur', # (이름이 같지만 '새' 지도 기준)
        'Mongala': 'Equateur',
        'Nord Ubangi': 'Equateur',
        'Sud Ubangi': 'Equateur',
        'Tshuapa': 'Equateur',

        # Kasai Occidental (standard) -> 2 new
        'Kasaï': 'Kasai Occidental',
        'Kasaï Central': 'Kasai Occidental',

        # Kasai Oriental (standard) -> 3 new
        'Kasai Oriental': 'Kasai Oriental', # (이름이 같지만 '새' 지도 기준)
        'Lomami': 'Kasai Oriental',
        'Sankuru': 'Kasai Oriental',

        # Bas-Congo (standard) -> 1 new (이름 변경)
        'Kongo Central': 'Bas-Congo'

        # Unchanged: 'Kinshasa', 'Maniema', 'Nord-Kivu', 'Sud-Kivu'
        # 이 4개는 롤백 매핑에 포함되지 않음 (아래에서 자동 처리)
    }

    # --- 3. (!!! 완료 !!!) 26개 새 주의 인구 데이터 (2019~2022년 추정치) ---
    # (Key는 disease_df의 2023년 지역명과 정확히 일치해야 함)
    population_data_drc = {
        # Katanga (4)
        'Haut-Katanga': 5718800,  # (2020)
        'Haut Lomami': 2957000,   # (2019)
        'Lualaba': 3183300,      # (2020)
        'Tanganyika': 3570000,   # (2019)

        # Bandundu (3)
        'Kwango': 2416000,      # (2019)
        'Kwilu': 6169000,       # (2019)
        'Mai-Ndombe': 2082000,  # (2019)

        # Orientale (4)
        'Bas-Uele': 1250000,    # (2019)
        'Haut Uele': 2046000,   # (2019)
        'Ituri': 4008000,       # (2019)
        'Tshopo': 2582000,      # (2019)

        # Equateur (5)
        'Equateur': 1905394,    # (2022)
        'Mongala': 1950000,     # (2019)
        'Nord Ubangi': 1425000, # (2019)
        'Sud Ubangi': 2987100,  # (2020)
        'Tshuapa': 1600000,     # (2019)

        # Kasai Occidental (2)
        'Kasaï': 3165000,         # (2019)
        'Kasaï Central': 3743000, # (2019)

        # Kasai Oriental (3)
        'Kasai Oriental': 3601000, # (2019)
        'Lomami': 2801000,         # (2019)
        'Sankuru': 2417000,        # (2019)

        # Bas-Congo (1)
        'Kongo Central': 6365000,  # (2019)

        # Unchanged (4)
        'Kinshasa': 13916000,     # (2019)
        'Maniema': 2654000,        # (2019)
        'Nord-Kivu': 7574000,      # (2019)
        'Sud-Kivu': 6565000       # (2019)
    }

    # --- 4. 2015년 이후 데이터 필터링 ---
    # (2015년 이후 모든 연도 데이터에 이 롤백 로직을 적용)
    mask_post_2015 = (disease_df['country'] == COUNTRY_NAME) & (disease_df['year'] == 2023)
    df_post_2015 = disease_df[mask_post_2015].copy()

    if df_post_2015.empty:
        print("2단계: 2015년 이후 DRC 데이터가 없어 롤백을 건너뜁니다.")
    else:
        # --- 5. 가중 평균 계산 ---

        # 5-1. "옛날 주" 이름 할당 (롤백 매핑 적용)
        df_post_2015['old_region_name'] = df_post_2015['region_name'].map(rollback_mapping_drc)

        # 5-2. 롤백이 필요 없는 4개 주(Kinshasa 등)는 원래 이름 유지
        df_post_2015['old_region_name'] = df_post_2015['old_region_name'].fillna(df_post_2015['region_name'])

        # 5-3. 인구 데이터 매핑 (해당 연도 인구 대신 2019-2022 추정치 사용)
        df_post_2015['pop'] = df_post_2015['region_name'].map(population_data_drc)

        # 5-4. 인구가 없는 지역 확인 (매핑 실패)
        if df_post_2015['pop'].isnull().any():
            print("!!! 경고: 인구 데이터가 누락된 지역이 있습니다. !!!")
            print(df_post_2015[df_post_2015['pop'].isnull()]['region_name'].unique())
            print("이 지역들은 가중 평균 계산에서 제외됩니다.")
            df_post_2015 = df_post_2015.dropna(subset=['pop']) # NaN 행 제거

        # 5-5. 가중 평균 분자(총 발병 건수) 계산
        df_post_2015['weighted_cases'] = df_post_2015['infection_rate'] * df_post_2015['pop']

        # 5-6. "옛날 주(old_region_name)" 기준으로 그룹화 및 합산
        # (중요: 'year'별로 그룹화해야 함)
        df_agg = df_post_2015.groupby(['country', 'year', 'old_region_name']).agg(
            total_weighted_cases=('weighted_cases', 'sum'),
            total_pop=('pop', 'sum')
        ).reset_index()

        # 5-7. 최종 가중 평균 (새로운 발병률) 계산
        df_agg['infection_rate'] = df_agg['total_weighted_cases'] / df_agg['total_pop']

        # 5-8. 컬럼 이름 원복 (standard와 맞춤)
        df_agg = df_agg.rename(columns={'old_region_name': 'region_name'})

        # 5-9. 원본(disease_df)에서 2015년 이후 DRC 행 삭제
        disease_df = disease_df.drop(disease_df[mask_post_2015].index)

        # 5-10. 롤백된 (df_agg) 데이터를 원본에 다시 추가
        # (disease_df의 컬럼 순서와 맞추기 위해 주요 컬럼만 선택)
        disease_df = pd.concat([disease_df, df_agg[['country', 'year', 'region_name', 'infection_rate']]], ignore_index=True)

        print("2단계: 2015년 이후 데이터 (가중 평균 롤백) 완료.")
    print("--- [DRC] 모든 작업 완료 ---")

except NameError:
    print("오류: 'disease_df'가 메모리에 없습니다. 먼저 로드해주세요.")
except Exception as e:
    print(f"예상치 못한 오류 발생: {e}")

--- [DRC] Democratic Republic of the Congo 시공간 롤백(Roll-back) 작업 시작 ---
2단계: 2015년 이후 데이터 (가중 평균 롤백) 완료.
--- [DRC] 모든 작업 완료 ---

In [ ]:
# 각 연도 매핑 테스트
drc_region_2007 = set(disease_df[(disease_df['country']=="Democratic Republic of the Congo") & (disease_df['year']==2007)]['region_name'])
drc_region_2023 = set(disease_df[(disease_df['country']=="Democratic Republic of the Congo") & (disease_df['year']==2023)]['region_name'])
drc_region_2013 = set(disease_df[(disease_df['country']=="Democratic Republic of the Congo") & (disease_df['year']==2013)]['region_name'])

drc_region_standard = set(standard_df[standard_df['ADM0_NAME']=="Democratic Republic of the Congo"]['ADM1_NAME'])

print(drc_region_2007-drc_region_standard)
print(drc_region_2023-drc_region_standard)
print(drc_region_2013-drc_region_standard)

print(drc_region_2023)
print(drc_region_standard)

set()
set()
set()
{'Kasai Oriental', 'Nord-Kivu', 'Sud-Kivu', 'Katanga', 'Kasai Occidental', 'Maniema', 'Bas-Congo', 'Orientale', 'Equateur', 'Kinshasa', 'Bandundu'}
{'Kasai Oriental', 'Nord-Kivu', 'Sud-Kivu', 'Katanga', 'Kasai Occidental', 'Maniema', 'Bas-Congo', 'Orientale', 'Equateur', 'Kinshasa', 'Bandundu'}

In [ ]:
disease_df[disease_df['country']=="Democratic Republic of the Congo"]

     year                           country       region_name  infection_rate
100  2007  Democratic Republic of the Congo          Bandundu        0.525210
101  2007  Democratic Republic of the Congo         Bas-Congo        1.376147
102  2007  Democratic Republic of the Congo          Equateur        1.179245
103  2007  Democratic Republic of the Congo  Kasai Occidental        0.718391
104  2007  Democratic Republic of the Congo    Kasai Oriental        1.593137
105  2007  Democratic Republic of the Congo           Katanga        1.985981
106  2007  Democratic Republic of the Congo          Kinshasa        1.876877
107  2007  Democratic Republic of the Congo           Maniema        0.462428
108  2007  Democratic Republic of the Congo         Nord-Kivu        1.335113
109  2007  Democratic Republic of the Congo         Orientale        2.264151
110  2007  Democratic Republic of the Congo          Sud-Kivu        1.966292
564  2013  Democratic Republic of the Congo          Bandundu        0.256520
565  2013  Democratic Republic of the Congo         Bas-Congo        0.430108
566  2013  Democratic Republic of the Congo          Equateur        0.843109
567  2013  Democratic Republic of the Congo  Kasai Occidental        0.494350
568  2013  Democratic Republic of the Congo    Kasai Oriental        1.275761
569  2013  Democratic Republic of the Congo           Katanga        1.091902
570  2013  Democratic Republic of the Congo          Kinshasa        1.523810
571  2013  Democratic Republic of the Congo           Maniema        1.799775
572  2013  Democratic Republic of the Congo         Nord-Kivu        0.931099
573  2013  Democratic Republic of the Congo         Orientale        1.819923
574  2013  Democratic Republic of the Congo          Sud-Kivu        0.509165
600  2023  Democratic Republic of the Congo          Bandundu        0.297359
601  2023  Democratic Republic of the Congo         Bas-Congo        0.844773
602  2023  Democratic Republic of the Congo          Equateur        0.829451
603  2023  Democratic Republic of the Congo  Kasai Occidental        0.475740
604  2023  Democratic Republic of the Congo    Kasai Oriental        0.655838
605  2023  Democratic Republic of the Congo           Katanga        1.307594
606  2023  Democratic Republic of the Congo          Kinshasa        0.422297
607  2023  Democratic Republic of the Congo           Maniema        0.394477
608  2023  Democratic Republic of the Congo         Nord-Kivu        0.806452
609  2023  Democratic Republic of the Congo         Orientale        2.533986
610  2023  Democratic Republic of the Congo          Sud-Kivu        0.503525

In [ ]:
until_drc_df = disease_df

##**Ethiopia**

#### **mapping pair**
- 'Addis Abeba':'Addis Ababa',
- 'Addis Adaba':'Addis Ababa',
- 'Affar':'Afar',
- 'Ben-Gumz':'Beneshangul Gumu',
- 'Benishangul':'Beneshangul Gumu',
- 'Benishangul-Gumuz':'Beneshangul Gumu',
- 'Harari':'Hareri',
- 'Oromiya':'Oromia',
- 'SNNP': 'SNNPR'

#### **특이사항**
-

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="Ethiopia"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="Ethiopia"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="Ethiopia"]['region_name'])))

ethiopia_mapping_dict = {
    'Addis Abeba':'Addis Ababa',
    'Addis Adaba':'Addis Ababa',
    'Affar':'Afar',
    'Ben-Gumz':'Beneshangul Gumu',
    'Benishangul':'Beneshangul Gumu',
    'Benishangul-Gumuz':'Beneshangul Gumu',
    'Harari':'Hareri',
    'Oromiya':'Oromia',
    'SNNP': 'SNNPR'
}

disease_df.loc[disease_df['country'] == 'Ethiopia', 'region_name'] = disease_df.loc[disease_df['country'] == 'Ethiopia', 'region_name'].replace(ethiopia_mapping_dict)

print("disease data after mapping")
new_ethiopia_df = disease_df[disease_df['country']=='Ethiopia']
print(new_ethiopia_df)

set(new_ethiopia_df['region_name']) - set(standard_df[standard_df['ADM0_NAME']=='Ethiopia']['ADM1_NAME'])

disease region name
['Addis Ababa', 'Addis Abeba', 'Addis Adaba', 'Afar', 'Affar', 'Amhara', 'Ben-Gumz', 'Benishangul', 'Benishangul-Gumuz', 'Dire Dawa', 'Gambela', 'Harari', 'Oromia', 'Oromiya', 'SNNP', 'SNNPR', 'Somali', 'Tigray']

standard region name
['Addis Ababa', 'Afar', 'Amhara', 'Beneshangul Gumu', 'Dire Dawa', 'Gambela', 'Hareri', 'Oromia', 'SNNPR', 'Somali', 'Tigray']



mismatch list
['Addis Abeba', 'Addis Adaba', 'Affar', 'Ben-Gumz', 'Benishangul', 'Benishangul-Gumuz', 'Harari', 'Oromiya', 'SNNP']
disease data after mapping
     year   country       region_name  infection_rate
129  2011  Ethiopia       Addis Ababa        4.878049
130  2011  Ethiopia              Afar        1.374113
131  2011  Ethiopia            Amhara        1.178240
132  2011  Ethiopia  Beneshangul Gumu        0.738007
133  2011  Ethiopia         Dire Dawa        3.646934
134  2011  Ethiopia           Gambela        3.909266
135  2011  Ethiopia            Hareri        2.699841
136  2011  Ethiopia            Oromia        1.021378
137  2011  Ethiopia             SNNPR        0.656635
138  2011  Ethiopia            Somali        1.019714
139  2011  Ethiopia            Tigray        1.723058
144  2005  Ethiopia       Addis Ababa        3.300330
145  2005  Ethiopia              Afar        1.140251
146  2005  Ethiopia            Amhara        1.253133
147  2005  Ethiopia  Beneshangul Gumu        0.450958
148  2005  Ethiopia         Dire Dawa        1.839080
149  2005  Ethiopia           Gambela        3.625731
150  2005  Ethiopia            Hareri        2.203568
151  2005  Ethiopia            Oromia        1.111586
152  2005  Ethiopia             SNNPR        0.279720
153  2005  Ethiopia            Somali        0.260417
154  2005  Ethiopia            Tigray        1.407349
184  2016  Ethiopia       Addis Ababa        3.519822
185  2016  Ethiopia              Afar        1.285634
186  2016  Ethiopia            Amhara        1.192504
187  2016  Ethiopia  Beneshangul Gumu        0.810127
188  2016  Ethiopia         Dire Dawa        2.670623
189  2016  Ethiopia           Gambela        4.516129
190  2016  Ethiopia            Hareri        2.677165
191  2016  Ethiopia            Oromia        0.664740
192  2016  Ethiopia             SNNPR        0.358744
193  2016  Ethiopia            Somali        0.091996
194  2016  Ethiopia            Tigray        1.075992

set()

In [ ]:
disease_df[disease_df['country']=="Ethiopia"]

     year   country        region_name  infection_rate
129  2011  Ethiopia        Addis Ababa        4.878049
130  2011  Ethiopia              Affar        1.374113
131  2011  Ethiopia             Amhara        1.178240
132  2011  Ethiopia  Benishangul-Gumuz        0.738007
133  2011  Ethiopia          Dire Dawa        3.646934
134  2011  Ethiopia            Gambela        3.909266
135  2011  Ethiopia             Harari        2.699841
136  2011  Ethiopia            Oromiya        1.021378
137  2011  Ethiopia               SNNP        0.656635
138  2011  Ethiopia             Somali        1.019714
139  2011  Ethiopia             Tigray        1.723058
144  2005  Ethiopia        Addis Abeba        3.300330
145  2005  Ethiopia               Afar        1.140251
146  2005  Ethiopia             Amhara        1.253133
147  2005  Ethiopia           Ben-Gumz        0.450958
148  2005  Ethiopia          Dire Dawa        1.839080
149  2005  Ethiopia            Gambela        3.625731
150  2005  Ethiopia             Harari        2.203568
151  2005  Ethiopia            Oromiya        1.111586
152  2005  Ethiopia               SNNP        0.279720
153  2005  Ethiopia             Somali        0.260417
154  2005  Ethiopia             Tigray        1.407349
184  2016  Ethiopia        Addis Adaba        3.519822
185  2016  Ethiopia               Afar        1.285634
186  2016  Ethiopia             Amhara        1.192504
187  2016  Ethiopia        Benishangul        0.810127
188  2016  Ethiopia          Dire Dawa        2.670623
189  2016  Ethiopia            Gambela        4.516129
190  2016  Ethiopia             Harari        2.677165
191  2016  Ethiopia             Oromia        0.664740
192  2016  Ethiopia              SNNPR        0.358744
193  2016  Ethiopia             Somali        0.091996
194  2016  Ethiopia             Tigray        1.075992

In [ ]:
until_ethioia_df = disease_df

In [ ]:
disease_df = until_ethioia_df

##**Gabon**

#### **mapping pair**
- (2012년 코드에서)
  - 'Ogooué Maritime': 'Ogooue-Maritime', # 2012년용
  - 'Ogooue-Lolo': 'Ogooue-lolo',         # 2012년용
        
- (2019년 코드에서)
  - 'Haut-Ogooué': 'Haut-Ogooue',
  - 'Moyen-Ogooué': 'Moyen-Ogooue',
  - 'Ngounié': 'Ngounie',
  - 'Ogooué-Ivindo': 'Ogooue-Ivindo',
  - 'Ogooué-Lolo': 'Ogooue-lolo',
  - 'Woleu-Ntem': 'Woleu-Ntem'

#### **특이사항**
- 'Libreville-Port-Gentil' : 2012년 데이터에만 존재하는 비표준 행이라서 삭제
- 'Estuaire (without Libreville)', 'Libreville' 에 대해서 Estuaire 하나의 행으로 합치기 진행
- 'Ogooué-Maritime (without Port-Gentil)', 'Port-Gentil'에 대해서 Ogooué-Maritime 하나의 행으로 합치기 진행

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="Gabon"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="Gabon"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="Gabon"]['region_name'])))

disease region name
['Estuaire', 'Estuaire (without Libreville)', 'Haut-Ogooué', 'Libreville', 'Libreville-Port-Gentil', 'Moyen-Ogooué', 'Ngounié', 'Nyanga', 'Ogooué Maritime', 'Ogooué-Ivindo', 'Ogooué-Lolo', 'Ogooué-Maritime (without Port-Gentil)', 'Port-Gentil', 'Woleu-Ntem']

standard region name
['Estuaire', 'Haut-Ogooue', 'Moyen-Ogooue', 'Ngounie', 'Nyanga', 'Ogooue-Ivindo', 'Ogooue-Maritime', 'Ogooue-lolo', 'Woleu-Ntem']



mismatch list
['Estuaire (without Libreville)', 'Haut-Ogooué', 'Libreville', 'Libreville-Port-Gentil', 'Moyen-Ogooué', 'Ngounié', 'Ogooué Maritime', 'Ogooué-Ivindo', 'Ogooué-Lolo', 'Ogooué-Maritime (without Port-Gentil)', 'Port-Gentil']

In [ ]:
# --- 1. 설정: 국가 이름 ---
COUNTRY_NAME = 'Gabon'

print(f"--- 가봉({COUNTRY_NAME}) 전체 데이터 정리 시작 ---")

try:
    # --- 2. [2012년 처리]: 비표준 행 삭제 ---
    # (2012년에만 존재하는 'Libreville-Port-Gentil' 삭제)
    regions_to_delete_2012 = ['Libreville-Port-Gentil']

    indices_to_drop_2012 = disease_df[
        (disease_df['country'] == COUNTRY_NAME) &
        (disease_df['year'] == 2012) &
        (disease_df['region_name'].isin(regions_to_delete_2012))
    ].index

    disease_df = disease_df.drop(indices_to_drop_2012)
    print(f"1단계 (2012년): 비표준 지역 {len(indices_to_drop_2012)}개 행 삭제 완료.")


    # --- 3. [2019년 처리]: 가중 평균 집계 ---

    # 3-1. 2019년 인구 추정치
    population_2019_gabon = {
        'Libreville': 850000,
        'Estuaire (without Libreville)': 160000,
        'Port-Gentil': 142000,
        'Ogooué-Maritime (without Port-Gentil)': 22000
    }

    # 3-2. 가중 평균 계산
    new_rows_2019 = []
    YEAR = 2019
    pop = population_2019_gabon

    # --- A. Estuaire / Libreville 합치기 ---
    regions_centre = ['Estuaire (without Libreville)', 'Libreville']
    df_centre_parts = disease_df[
        (disease_df['country'] == COUNTRY_NAME) &
        (disease_df['year'] == YEAR) &
        (disease_df['region_name'].isin(regions_centre))
    ]

    if len(df_centre_parts) == 2:
        rate_A = df_centre_parts.loc[df_centre_parts['region_name'] == 'Estuaire (without Libreville)', 'infection_rate'].iloc[0]
        pop_A = pop['Estuaire (without Libreville)']
        rate_B = df_centre_parts.loc[df_centre_parts['region_name'] == 'Libreville', 'infection_rate'].iloc[0]
        pop_B = pop['Libreville']

        total_cases = (rate_A * pop_A) + (rate_B * pop_B)
        total_pop = pop_A + pop_B
        new_rate = total_cases / total_pop

        new_rows_2019.append({'country': COUNTRY_NAME, 'year': YEAR, 'region_name': 'Estuaire', 'infection_rate': new_rate})
    else:
        print(f"정보: {YEAR}년 Estuaire/Libreville 집계 대상이 없거나 부족합니다.")

    # --- B. Ogooué-Maritime / Port-Gentil 합치기 ---
    regions_littoral = ['Ogooué-Maritime (without Port-Gentil)', 'Port-Gentil']
    df_littoral_parts = disease_df[
        (disease_df['country'] == COUNTRY_NAME) &
        (disease_df['year'] == YEAR) &
        (disease_df['region_name'].isin(regions_littoral))
    ]

    if len(df_littoral_parts) == 2:
        rate_A = df_littoral_parts.loc[df_littoral_parts['region_name'] == 'Ogooué-Maritime (without Port-Gentil)', 'infection_rate'].iloc[0]
        pop_A = pop['Ogooué-Maritime (without Port-Gentil)']
        rate_B = df_littoral_parts.loc[df_littoral_parts['region_name'] == 'Port-Gentil', 'infection_rate'].iloc[0]
        pop_B = pop['Port-Gentil']

        total_cases = (rate_A * pop_A) + (rate_B * pop_B)
        total_pop = pop_A + pop_B
        new_rate = total_cases / total_pop

        new_rows_2019.append({'country': COUNTRY_NAME, 'year': YEAR, 'region_name': 'Ogooue-Maritime', 'infection_rate': new_rate})
    else:
        print(f"정보: {YEAR}년 Ogooué-Maritime/Port-Gentil 집계 대상이 없거나 부족합니다.")

    # 3-3. 2019년 비표준 행 삭제
    regions_to_delete_2019 = [
        'Estuaire (without Libreville)', 'Libreville',
        'Ogooué-Maritime (without Port-Gentil)', 'Port-Gentil'
    ]
    indices_to_drop_2019 = disease_df[
        (disease_df['country'] == COUNTRY_NAME) &
        (disease_df['year'] == YEAR) &
        (disease_df['region_name'].isin(regions_to_delete_2019))
    ].index

    disease_df = disease_df.drop(indices_to_drop_2019)

    # 3-4. 새로 집계된 2019년 행 추가
    if new_rows_2019:
        disease_df = pd.concat([disease_df, pd.DataFrame(new_rows_2019)], ignore_index=True)

    print(f"2단계 (2019년): 가중 평균 집계 및 {len(indices_to_drop_2019)}개 행 삭제 완료.")


    # --- 4. [전체 연도 처리]: 통합 오타 매핑 ---
    # (2012년과 2019년 코드의 모든 오타를 하나로 합침)
    gabon_master_mapping = {
        # (2012년 코드에서)
        'Ogooué Maritime': 'Ogooue-Maritime', # 2012년용
        'Ogooue-Lolo': 'Ogooue-lolo',         # 2012년용

        # (2019년 코드에서)
        'Haut-Ogooué': 'Haut-Ogooue',
        'Moyen-Ogooué': 'Moyen-Ogooue',
        'Ngounié': 'Ngounie',
        'Ogooué-Ivindo': 'Ogooue-Ivindo',
        'Ogooué-Lolo': 'Ogooue-lolo',
        'Woleu-Ntem': 'Woleu-Ntem'
    }

    mask = (disease_df['country'] == COUNTRY_NAME)
    disease_df.loc[mask, 'region_name'] = disease_df.loc[mask, 'region_name'].replace(gabon_master_mapping)
    print("3단계 (전체 연도): 단순 오타 매핑 완료.")

    print(f"\n--- [최종 작업 완료] 가봉({COUNTRY_NAME}) 데이터 정리 완료 ---")

except NameError:
    print("오류: 'disease_df'가 메모리에 없습니다. 먼저 로드해주세요.")
except Exception as e:
    print(f"예상치 못한 오류 발생: {e}")

--- 가봉(Gabon) 전체 데이터 정리 시작 ---
1단계 (2012년): 비표준 지역 1개 행 삭제 완료.
2단계 (2019년): 가중 평균 집계 및 4개 행 삭제 완료.
3단계 (전체 연도): 단순 오타 매핑 완료.

--- [최종 작업 완료] 가봉(Gabon) 데이터 정리 완료 ---

In [ ]:
# 각 연도 매핑 테스트
gabon_region_2019 = set(disease_df[(disease_df['country']=="Gabon") & (disease_df['year']==2019)]['region_name'])
gabon_region_2012 = set(disease_df[(disease_df['country']=="Gabon") & (disease_df['year']==2012)]['region_name'])

gabon_region_standard = set(standard_df[standard_df['ADM0_NAME']=="Gabon"]['ADM1_NAME'])

#gabon_region_2012-gabon_region_standard
gabon_region_2019-gabon_region_standard

set()

In [ ]:
disease_df[disease_df['country']=="Gabon"]

     year country                            region_name  infection_rate
163  2019   Gabon          Estuaire (without Libreville)        4.251550
164  2019   Gabon                            Haut-Ogooué        2.473498
165  2019   Gabon                             Libreville        4.198211
166  2019   Gabon                           Moyen-Ogooué        4.571904
167  2019   Gabon                                Ngounié        4.343720
168  2019   Gabon                                 Nyanga        5.284553
169  2019   Gabon                          Ogooué-Ivindo        2.564103
170  2019   Gabon                            Ogooué-Lolo        3.082437
171  2019   Gabon  Ogooué-Maritime (without Port-Gentil)        4.206242
172  2019   Gabon                            Port-Gentil        4.822335
173  2019   Gabon                             Woleu-Ntem        5.487411
174  2012   Gabon                               Estuaire        4.188482
175  2012   Gabon                            Haut-Ogooué        4.155375
176  2012   Gabon                 Libreville-Port-Gentil        4.327424
177  2012   Gabon                           Moyen-Ogooué        5.928412
178  2012   Gabon                                Ngounié        4.684838
179  2012   Gabon                                 Nyanga        3.944563
180  2012   Gabon                        Ogooué Maritime        4.842615
181  2012   Gabon                          Ogooué-Ivindo        2.323780
182  2012   Gabon                            Ogooué-Lolo        3.261883
183  2012   Gabon                             Woleu-Ntem        8.324084

In [ ]:
until_gabon_df = disease_df

##**Gambia**

#### **mapping pair**
- 'Kanifing': 'Kanifing Municipal Council'
- 'Basse': 'Upper River'
- 'Kerewan': 'North Bank'
- 'Mansakonko': 'Lower River'
- 'Brikama': 'West Coast'
- Janjanbureh + Kuntaur -(가중평균)-> Central River

#### **특이사항**
- disease dataset의 region 이름들은 level1의 이름이 아닌 해당 지방자치단체의 수도를 나타냄
-

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="Gambia"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="Gambia"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="Gambia"]['region_name'])))

disease region name
['Banjul', 'Basse', 'Brikama', 'Janjanbureh', 'Kanifing', 'Kerewan', 'Kuntaur', 'Mansakonko']

standard region name
['Central River', 'Kanifing Municipal Council', 'Lower River', 'North Bank', 'Upper River', 'West Coast']



mismatch list
['Banjul', 'Basse', 'Brikama', 'Janjanbureh', 'Kanifing', 'Kerewan', 'Kuntaur', 'Mansakonko']

In [ ]:
# --- 1. 설정: 국가 및 연도 ---
COUNTRY_NAME = 'Gambia'
YEAR = 2013

# --- 2. 2013년 인구 데이터 (GBoS 2013 Census) ---
# (가중 평균이 필요한 'Central River' 지역구에 대해서만 정의)
population_2013_gambia = {
    'Janjanbureh': 125204,
    'Kuntaur': 96703
}

print(f"--- 감비아({COUNTRY_NAME}) {YEAR}년 데이터 집계 시작 ---")

try:
    # --- 3. [2:1 집계] 'Central River' 가중 평균 ---
    # (Janjanbureh + Kuntaur -> Central River)

    regions_to_aggregate = ['Janjanbureh', 'Kuntaur']
    new_region_name = 'Central River'

    # 2013년 & 감비아 & 두 지역 데이터 필터링
    df_parts = disease_df[
        (disease_df['country'] == COUNTRY_NAME) &
        (disease_df['year'] == YEAR) &
        (disease_df['region_name'].isin(regions_to_aggregate))
    ]

    new_row_df = pd.DataFrame() # 빈 DataFrame으로 시작

    if len(df_parts) == 2:
        # 2013년 인구 기반으로 가중 평균 계산
        pop_A = population_2013_gambia['Janjanbureh']
        rate_A = df_parts.loc[df_parts['region_name'] == 'Janjanbureh', 'infection_rate'].iloc[0]

        pop_B = population_2013_gambia['Kuntaur']
        rate_B = df_parts.loc[df_parts['region_name'] == 'Kuntaur', 'infection_rate'].iloc[0]

        total_cases = (rate_A * pop_A) + (rate_B * pop_B)
        total_pop = pop_A + pop_B
        new_rate = total_cases / total_pop

        # 새 행 생성
        new_row = {
            'country': COUNTRY_NAME,
            'year': YEAR,
            'region_name': new_region_name,
            'infection_rate': new_rate
        }
        new_row_df = pd.DataFrame([new_row])
        print(f"1단계: '{YEAR} {new_region_name}' 생성 완료 (Rate: {new_rate:.6f})")
    else:
        print(f"1단계 경고: {YEAR}년 Janjanbureh/Kuntaur 데이터가 2개가 아닙니다. 집계를 건너뜁니다.")

    # --- 4. 불필요한 행 삭제 ---

    # 'Banjul' (standard에 없음) + 집계에 사용된 2개 지역
    regions_to_delete_gambia = ['Banjul', 'Janjanbureh', 'Kuntaur']

    indices_to_drop = disease_df[
        (disease_df['country'] == COUNTRY_NAME) &
        (disease_df['year'] == YEAR) &
        (disease_df['region_name'].isin(regions_to_delete_gambia))
    ].index

    disease_df = disease_df.drop(indices_to_drop)
    print(f"2단계: {YEAR}년 비표준 행 {len(indices_to_drop)}개 삭제 완료.")

    # --- 5. 새 집계 행 추가 ---
    if not new_row_df.empty:
        disease_df = pd.concat([disease_df, new_row_df], ignore_index=True)

    # --- 6. 단순 이름 매핑 (1:1 Rename) ---

    # (2013년 데이터에만 적용)
    mapping_dict_gambia = {
        'Kanifing': 'Kanifing Municipal Council',
        'Basse': 'Upper River',
        'Kerewan': 'North Bank',
        'Mansakonko': 'Lower River',
        'Brikama': 'West Coast'
    }

    mask = (disease_df['country'] == COUNTRY_NAME) & (disease_df['year'] == YEAR)
    disease_df.loc[mask, 'region_name'] = disease_df.loc[mask, 'region_name'].replace(mapping_dict_gambia)
    print("3단계: 1:1 단순 이름 매핑(Rename) 완료.")

    print(f"\n--- [최종 작업 완료] 감비아({COUNTRY_NAME}) 데이터 정리 완료 ---")

    # --- 7. 검증 ---
    print("\n--- 검증 (2013년) ---")
    standard_gambia_set = set(['Central River', 'Kanifing Municipal Council', 'Lower River', 'North Bank', 'Upper River', 'West Coast'])
    disease_set_2013 = set(disease_df[(disease_df['country'] == COUNTRY_NAME) & (disease_df['year'] == YEAR)]['region_name'])

    verification_result = disease_set_2013 - standard_gambia_set
    print(f"검증 결과 (set()가 나와야 함): {verification_result}")

except NameError:
    print("오류: 'disease_df'가 메모리에 없습니다. 먼저 로드해주세요.")
except KeyError as e:
    print(f"오류: 컬럼 이름({e})을 찾을 수 없습니다. 'infection_rate' 컬럼이 맞는지 확인하세요.")
except Exception as e:
    print(f"예상치 못한 오류 발생: {e}")

--- 감비아(Gambia) 2013년 데이터 집계 시작 ---
1단계: '2013 Central River' 생성 완료 (Rate: 2.097871)
2단계: 2013년 비표준 행 3개 삭제 완료.
3단계: 1:1 단순 이름 매핑(Rename) 완료.

--- [최종 작업 완료] 감비아(Gambia) 데이터 정리 완료 ---

--- 검증 (2013년) ---
검증 결과 (set()가 나와야 함): set()

In [ ]:
disease_df[disease_df['country']=="Gambia"]

     year country  region_name  infection_rate
155  2013  Gambia       Banjul        1.233184
156  2013  Gambia        Basse        0.792752
157  2013  Gambia      Brikama        2.205882
158  2013  Gambia  Janjanbureh        2.611940
159  2013  Gambia     Kanifing        1.807229
160  2013  Gambia      Kerewan        1.288245
161  2013  Gambia      Kuntaur        1.432292
162  2013  Gambia   Mansakonko        2.564103

##**Guinea, Kenya**

#### **mapping pair**
- guinea
  - 'Boké':'Boke',
  - 'Labé':'Labe',
  - "N'Zérékoré":'Nzerekore'
- kenya
  - 'Northeastern' : 'North Eastern'
#### **특이사항**

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="Guinea"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="Guinea"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="Guinea"]['region_name'])))

guinea_mapping_dict = {
    'Boké':'Boke',
    'Labé':'Labe',
    "N'Zérékoré":'Nzerekore'
}

disease_df.loc[disease_df['country'] == 'Guinea', 'region_name'] = disease_df.loc[disease_df['country'] == 'Guinea', 'region_name'].replace(guinea_mapping_dict)

print("disease data after mapping")
new_guinea_df = disease_df[disease_df['country']=='Guinea']
print(new_guinea_df)

set(new_guinea_df['region_name']) - set(standard_df[standard_df['ADM0_NAME']=='Guinea']['ADM1_NAME'])

disease region name
['Boké', 'Conakry', 'Faranah', 'Kankan', 'Kindia', 'Labé', 'Mamou', "N'Zérékoré"]

standard region name
['Boke', 'Conakry', 'Faranah', 'Kankan', 'Kindia', 'Labe', 'Mamou', 'Nzerekore']



mismatch list
['Boké', 'Labé', "N'Zérékoré"]
disease data after mapping
     year country region_name  infection_rate
187  2012  Guinea        Boke        1.612903
188  2012  Guinea     Conakry        2.921841
189  2012  Guinea     Faranah        1.668211
190  2012  Guinea      Kankan        1.844091
191  2012  Guinea      Kindia        1.515152
192  2012  Guinea        Labe        1.871345
193  2012  Guinea       Mamou        1.775148
194  2012  Guinea   Nzerekore        1.939292
195  2018  Guinea        Boke        2.195307
196  2018  Guinea     Conakry        1.767677
197  2018  Guinea     Faranah        1.053556
198  2018  Guinea      Kankan        0.596252
199  2018  Guinea      Kindia        1.788909
200  2018  Guinea        Labe        1.958525
201  2018  Guinea       Mamou        0.931677
202  2018  Guinea   Nzerekore        1.294964
203  2005  Guinea        Boke        1.328904
204  2005  Guinea     Conakry        3.005780
205  2005  Guinea     Faranah        1.515152
206  2005  Guinea      Kankan        1.696833
207  2005  Guinea      Kindia        0.874317
208  2005  Guinea        Labe        1.866252
209  2005  Guinea       Mamou        0.957592
210  2005  Guinea   Nzerekore        1.255605

set()

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="Kenya"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="Kenya"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="Kenya"]['region_name'])))

kenya_mapping_dict = {
    'Northeastern' : 'North Eastern'
}

disease_df.loc[disease_df['country'] == 'Kenya', 'region_name'] = disease_df.loc[disease_df['country'] == 'Kenya', 'region_name'].replace(kenya_mapping_dict)

print("disease data after mapping")
new_kenya_df = disease_df[disease_df['country']=='Kenya']
print(new_kenya_df)

set(new_kenya_df['region_name']) - set(standard_df[standard_df['ADM0_NAME']=='Kenya']['ADM1_NAME'])

disease region name
['Central', 'Coast', 'Eastern', 'Nairobi', 'North Eastern', 'Northeastern', 'Nyanza', 'Rift Valley', 'Western']

standard region name
['Central', 'Coast', 'Eastern', 'Nairobi', 'North Eastern', 'Nyanza', 'Rift Valley', 'Western']



mismatch list
['Northeastern']
disease data after mapping
     year country    region_name  infection_rate
261  2008   Kenya        Central        4.743590
262  2008   Kenya          Coast        4.613734
263  2008   Kenya        Eastern        3.161222
264  2008   Kenya        Nairobi        7.643312
265  2008   Kenya  North Eastern        0.963855
266  2008   Kenya         Nyanza       16.281139
267  2008   Kenya    Rift Valley        5.156538
268  2008   Kenya        Western        7.204301
269  2003   Kenya        Central        3.264490
270  2003   Kenya          Coast        4.290092
271  2003   Kenya        Eastern        3.505355
272  2003   Kenya        Nairobi        4.628949
273  2003   Kenya  North Eastern        0.000000
274  2003   Kenya         Nyanza       12.535885
275  2003   Kenya    Rift Valley        3.750000
276  2003   Kenya        Western        4.662698

set()

In [ ]:
disease_df[disease_df['country']=='Kenya']

     year country    region_name  infection_rate
261  2008   Kenya        Central        4.743590
262  2008   Kenya          Coast        4.613734
263  2008   Kenya        Eastern        3.161222
264  2008   Kenya        Nairobi        7.643312
265  2008   Kenya   Northeastern        0.963855
266  2008   Kenya         Nyanza       16.281139
267  2008   Kenya    Rift Valley        5.156538
268  2008   Kenya        Western        7.204301
269  2003   Kenya        Central        3.264490
270  2003   Kenya          Coast        4.290092
271  2003   Kenya        Eastern        3.505355
272  2003   Kenya        Nairobi        4.628949
273  2003   Kenya  North Eastern        0.000000
274  2003   Kenya         Nyanza       12.535885
275  2003   Kenya    Rift Valley        3.750000
276  2003   Kenya        Western        4.662698

In [ ]:
until_kenya_df = disease_df

##**Lesotho**

#### **mapping pair**
- 'Botha-bothe':'Butha Buthe'
- 'Butha-Bothe':'Butha Buthe'
- 'Butha-Buthe':'Butha Buthe'
- "Mohale's hoek":"Mohale's Hoek"
- "Qacha's-Nek":"Qacha's Nek"
- "Qacha's-nek":"Qacha's Nek"
- "Qasha's Nek":"Qacha's Nek"
- 'Thaba-Tseka':'Thaba Tseka'
#### **특이사항**

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="Lesotho"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="Lesotho"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="Lesotho"]['region_name'])))

lesotho_mapping_dict = {
    'Botha-bothe':'Butha Buthe',
    'Butha-Bothe':'Butha Buthe',
    'Butha-Buthe':'Butha Buthe',
    "Mohale's hoek":"Mohale's Hoek",
    "Qacha's-Nek":"Qacha's Nek",
    "Qacha's-nek":"Qacha's Nek",
    "Qasha's Nek":"Qacha's Nek",
    'Thaba-Tseka':'Thaba Tseka'
}

disease_df.loc[disease_df['country'] == 'Lesotho', 'region_name'] = disease_df.loc[disease_df['country'] == 'Lesotho', 'region_name'].replace(lesotho_mapping_dict)

print("disease data after mapping")
new_lesotho_df = disease_df[disease_df['country']=='Lesotho']
print(new_lesotho_df)

set(new_lesotho_df['region_name']) - set(standard_df[standard_df['ADM0_NAME']=='Lesotho']['ADM1_NAME'])

disease region name
['Berea', 'Botha-bothe', 'Butha-Bothe', 'Butha-Buthe', 'Leribe', 'Mafeteng', 'Maseru', "Mohale's Hoek", "Mohale's hoek", 'Mokhotlong', "Qacha's-Nek", "Qacha's-nek", "Qasha's Nek", 'Quthing', 'Thaba Tseka', 'Thaba-Tseka']

standard region name
['Berea', 'Butha Buthe', 'Leribe', 'Mafeteng', 'Maseru', "Mohale's Hoek", 'Mokhotlong', "Qacha's Nek", 'Quthing', 'Thaba Tseka']



mismatch list
['Botha-bothe', 'Butha-Bothe', 'Butha-Buthe', "Mohale's hoek", "Qacha's-Nek", "Qacha's-nek", "Qasha's Nek", 'Thaba-Tseka']
disease data after mapping
     year  country    region_name  infection_rate
231  2014  Lesotho          Berea       25.986395
232  2014  Lesotho    Butha Buthe       21.071429
233  2014  Lesotho         Leribe       26.049204
234  2014  Lesotho       Mafeteng       25.333333
235  2014  Lesotho         Maseru       27.035831
236  2014  Lesotho  Mohale's Hoek       22.431507
237  2014  Lesotho     Mokhotlong       20.000000
238  2014  Lesotho    Qacha's Nek       21.330724
239  2014  Lesotho        Quthing       22.452830
240  2014  Lesotho    Thaba Tseka       24.629630
241  2009  Lesotho          Berea       20.793434
242  2009  Lesotho    Butha Buthe       15.359477
243  2009  Lesotho         Leribe       23.638778
244  2009  Lesotho       Mafeteng       20.956399
245  2009  Lesotho         Maseru       27.073403
246  2009  Lesotho  Mohale's Hoek       24.812030
247  2009  Lesotho     Mokhotlong       21.492537
248  2009  Lesotho    Qacha's Nek       22.043011
249  2009  Lesotho        Quthing       22.496148
250  2009  Lesotho    Thaba Tseka       19.971469
251  2004  Lesotho          Berea       17.537313
252  2004  Lesotho    Butha Buthe       14.285714
253  2004  Lesotho         Leribe       21.365360
254  2004  Lesotho       Mafeteng       17.918314
255  2004  Lesotho         Maseru       14.592275
256  2004  Lesotho  Mohale's Hoek       14.417532
257  2004  Lesotho     Mokhotlong       12.857143
258  2004  Lesotho    Qacha's Nek       19.215686
259  2004  Lesotho        Quthing       18.549747
260  2004  Lesotho    Thaba Tseka       16.504854

set()

In [ ]:
disease_df[disease_df['country']=='Lesotho']

     year  country    region_name  infection_rate
231  2014  Lesotho          Berea       25.986395
232  2014  Lesotho    Botha-bothe       21.071429
233  2014  Lesotho         Leribe       26.049204
234  2014  Lesotho       Mafeteng       25.333333
235  2014  Lesotho         Maseru       27.035831
236  2014  Lesotho  Mohale's hoek       22.431507
237  2014  Lesotho     Mokhotlong       20.000000
238  2014  Lesotho    Qacha's-nek       21.330724
239  2014  Lesotho        Quthing       22.452830
240  2014  Lesotho    Thaba Tseka       24.629630
241  2009  Lesotho          Berea       20.793434
242  2009  Lesotho    Butha-Bothe       15.359477
243  2009  Lesotho         Leribe       23.638778
244  2009  Lesotho       Mafeteng       20.956399
245  2009  Lesotho         Maseru       27.073403
246  2009  Lesotho  Mohale's Hoek       24.812030
247  2009  Lesotho     Mokhotlong       21.492537
248  2009  Lesotho    Qacha's-Nek       22.043011
249  2009  Lesotho        Quthing       22.496148
250  2009  Lesotho    Thaba-Tseka       19.971469
251  2004  Lesotho          Berea       17.537313
252  2004  Lesotho    Butha-Buthe       14.285714
253  2004  Lesotho         Leribe       21.365360
254  2004  Lesotho       Mafeteng       17.918314
255  2004  Lesotho         Maseru       14.592275
256  2004  Lesotho  Mohale's Hoek       14.417532
257  2004  Lesotho     Mokhotlong       12.857143
258  2004  Lesotho    Qasha's Nek       19.215686
259  2004  Lesotho        Quthing       18.549747
260  2004  Lesotho    Thaba-Tseka       16.504854

In [ ]:
until_lesotho_df = disease_df

##**Liberia**

#### **mapping pair**

#### **특이사항**
- disease region name (6개) = 비표준 보건/관리 구역 (Health/Admin Zones)
  - 'Monrovia', 'North Central', 'North Western' 등 6개는 라이베리아의 공식 Level 1 행정구역이 전혀 아닙니다.
  - 'Monrovia'는 수도(Capital City)이며, standard의 'Montserrado' 주(County) 안에 있습니다.
  - 'North Central', 'North Western', 'South Eastern A' 등은 disease 데이터를 수집한 기관(예: 보건부, WHO)이 15개의 공식 주(County)를 임의로 묶어서 만든 5개의 거대 "관리 구역(Zone)"입니다.

- standard로 활용되는 africa shp에는 올바르게 level1 지역들이 존재하지만, 'Monrovia', 'North Central', 'North Western' 등의 큼직한 분류는 올바른 level1 지역들로 쪼개기에도 너무 어렵기에 삭제하는 게 최선..

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="Liberia"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="Liberia"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="Liberia"]['region_name'])))

lesotho_mapping_dict = {}

disease region name
['Monrovia', 'North Central', 'North Western', 'South Central', 'South Eastern A', 'South Eastern B']

standard region name
['Bomi', 'Bong', 'Gbarpolu', 'Grand Bassa', 'Grand Cape Mount', 'Grand Gedeh', 'Grand Kru', 'Lofa', 'Margibi', 'Maryland', 'Montserrado', 'Nimba', 'River Gee', 'Rivercess', 'Sinoe']



mismatch list
['Monrovia', 'North Central', 'North Western', 'South Central', 'South Eastern A', 'South Eastern B']

In [ ]:
disease_df[disease_df['country']=='Liberia']

Empty DataFrame
Columns: [year, country, region_name, infection_rate]
Index: []

In [ ]:
disease_df = disease_df[disease_df['country'] != 'Liberia']

In [ ]:
until_liberia_df = disease_df

##**Malawi**

#### **mapping pair**
- 'Central': 'Central Region',
- 'Central region':'Central Region',
- 'Northern':'Northern Region',
- 'Northern region':'Northern Region',
- 'Southern':'Southern Region',
- 'Southern region':'Southern Region'

#### **특이사항**

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="Malawi"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="Malawi"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="Malawi"]['region_name'])))

malawi_mapping_dict = {
    'Central': 'Central Region',
    'Central region':'Central Region',
    'Northern':'Northern Region',
    'Northern region':'Northern Region',
    'Southern':'Southern Region',
    'Southern region':'Southern Region'
}


disease_df.loc[disease_df['country'] == 'Malawi', 'region_name'] = disease_df.loc[disease_df['country'] == 'Malawi', 'region_name'].replace(malawi_mapping_dict)

print("disease data after mapping")
new_malawi_df = disease_df[disease_df['country']=='Malawi']
print(new_malawi_df)

set(new_malawi_df['region_name']) - set(standard_df[standard_df['ADM0_NAME']=='Malawi']['ADM1_NAME'])

disease region name
['Central', 'Central region', 'Northern', 'Northern region', 'Southern', 'Southern region']

standard region name
['Area under National Administration', 'Central Region', 'Northern Region', 'Southern Region']



mismatch list
['Central', 'Central region', 'Northern', 'Northern region', 'Southern', 'Southern region']
disease data after mapping
     year country      region_name  infection_rate
277  2010  Malawi   Central Region        6.835443
278  2010  Malawi  Northern Region        7.184693
279  2010  Malawi  Southern Region       13.887647
280  2004  Malawi   Central Region        7.627119
281  2004  Malawi  Northern Region        8.391608
282  2004  Malawi  Southern Region       17.464573
294  2015  Malawi   Central Region        5.867111
295  2015  Malawi  Northern Region        6.812735
296  2015  Malawi  Southern Region       12.630496

set()

In [ ]:
disease_df[disease_df['country']=='Malawi']

     year country      region_name  infection_rate
277  2010  Malawi          Central        6.835443
278  2010  Malawi         Northern        7.184693
279  2010  Malawi         Southern       13.887647
280  2004  Malawi          Central        7.627119
281  2004  Malawi         Northern        8.391608
282  2004  Malawi         Southern       17.464573
294  2015  Malawi   Central region        5.867111
295  2015  Malawi  Northern region        6.812735
296  2015  Malawi  Southern region       12.630496

In [ ]:
until_malawi_df = disease_df

In [ ]:
disease_df = until_malawi_df

##**Mozambique,Niger**

#### **mapping pair**
- mozambique
  - Maputo cidade + Maputo provincia -(가중평균)-> Maputo
  - 'Cabo delgado': 'Cabo Delgado',
  - 'Zambézia': 'Zambezia'
- niger
  - 'Tillabéri':'Tillaberi'
#### **특이사항**

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="Mozambique"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="Mozambique"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="Mozambique"]['region_name'])))

malawi_mapping_dict = {
#    'Cabo delgado':'Cabo delgado',
#    'Maputo Cidade':
}

disease region name
['Cabo Delgado', 'Cabo delgado', 'Gaza', 'Inhambane', 'Manica', 'Maputo Cidade', 'Maputo Provincia', 'Maputo cidade', 'Maputo provincia', 'Nampula', 'Niassa', 'Sofala', 'Tete', 'Zambezia', 'Zambézia']

standard region name
['Cabo Delgado', 'Gaza', 'Inhambane', 'Lago niassa', 'Manica', 'Maputo', 'Nampula', 'Niassa', 'Sofala', 'Tete', 'Zambezia']



mismatch list
['Cabo delgado', 'Maputo Cidade', 'Maputo Provincia', 'Maputo cidade', 'Maputo provincia', 'Zambézia']

In [ ]:
# --- 1. 설정: 국가 이름 및 인구 데이터 ---
COUNTRY_NAME = 'Mozambique'

population_data_mozambique = {
    2009: {
        'Maputo Cidade': 1120000,
        'Maputo Provincia': 1300000
    },
    2015: {
        'Maputo Cidade': 1100000,
        'Maputo Provincia': 1720000
    }
}

print(f"--- 모잠비크({COUNTRY_NAME}) 데이터 정리 시작 ---")

try:
    # --- 2. [전체 연도] 1단계: 단순 오타 및 표기법 통일 ---
    # (이 작업을 먼저 해야 가중 평균 집계가 올바르게 작동합니다)
    mozambique_master_mapping = {
        # Maputo 오타 통일
        'Maputo cidade': 'Maputo Cidade',
        'Maputo provincia': 'Maputo Provincia',
        # Cabo Delgado 오타 통일
        'Cabo delgado': 'Cabo Delgado',
        # Zambezia 악센트 통일
        'Zambézia': 'Zambezia'
    }

    mask = (disease_df['country'] == COUNTRY_NAME)
    disease_df.loc[mask, 'region_name'] = disease_df.loc[mask, 'region_name'].replace(mozambique_master_mapping)
    print("1단계: 전체 연도 오타/표기법 통일 완료.")

    # --- 3. [2009, 2015년] 2단계: 가중 평균 집계 (Maputo 롤백) ---
    years_to_process = [2009, 2015]
    new_rows_mozambique = [] # 합쳐진 행들을 임시 저장
    indices_to_drop_mozambique = pd.Index([]) # 삭제할 인덱스 저장

    for year in years_to_process:
        print(f"\n--- {year}년 데이터 집계 시작 ---")
        pop = population_data_mozambique.get(year)
        if not pop:
            print(f"경고: {year}년 인구 데이터가 없습니다. 건너뜁니다.")
            continue

        # --- A. Maputo Cidade / Provincia 합치기 ---
        regions_to_aggregate = ['Maputo Cidade', 'Maputo Provincia']
        df_parts = disease_df[
            (disease_df['country'] == COUNTRY_NAME) &
            (disease_df['year'] == year) &
            (disease_df['region_name'].isin(regions_to_aggregate))
        ]

        if len(df_parts) == 2:
            rate_A = df_parts.loc[df_parts['region_name'] == 'Maputo Cidade', 'infection_rate'].iloc[0]
            pop_A = pop['Maputo Cidade']

            rate_B = df_parts.loc[df_parts['region_name'] == 'Maputo Provincia', 'infection_rate'].iloc[0]
            pop_B = pop['Maputo Provincia']

            # 가중 평균 계산
            total_cases = (rate_A * pop_A) + (rate_B * pop_B)
            total_pop = pop_A + pop_B
            new_rate = total_cases / total_pop

            # (중요) Standard 이름('Maputo')으로 새 행 생성
            new_rows_mozambique.append({
                'country': COUNTRY_NAME,
                'year': year,
                'region_name': 'Maputo', # Standard 이름
                'infection_rate': new_rate
            })

            # 집계에 사용된 원본 행 인덱스 저장
            indices_to_drop_mozambique = indices_to_drop_mozambique.union(df_parts.index)
            print(f"'{year} Maputo' 생성 완료 (Rate: {new_rate:.6f})")

        else:
            print(f"경고: {year}년 Maputo Cidade/Provincia 데이터가 2개가 아닙니다. 집계를 건너뜁니다.")

    # --- 4. 3단계: 원본 행 삭제 및 새 집계 행 추가 ---

    # 4-1. 집계에 사용된 원본 행 삭제
    disease_df = disease_df.drop(indices_to_drop_mozambique)
    print(f"\n3단계: 집계에 사용된 {len(indices_to_drop_mozambique)}개 행 삭제 완료.")

    # 4-2. 새로 생성된 'Maputo' 행들을 원본에 추가
    if new_rows_mozambique:
        disease_df = pd.concat([disease_df, pd.DataFrame(new_rows_mozambique)], ignore_index=True)
        print("가중 평균으로 집계된 새 'Maputo' 행 추가 완료.")

    print(f"\n--- [최종 작업 완료] 모잠비크({COUNTRY_NAME}) 데이터 정리 완료 ---")

    # --- 5. 검증 ---
    print("\n--- 검증 (2009, 2015년) ---")
    standard_mozambique_set = set(['Cabo Delgado', 'Gaza', 'Inhambane', 'Lago niassa', 'Manica', 'Maputo', 'Nampula', 'Niassa', 'Sofala', 'Tete', 'Zambezia'])
    disease_set_processed = set(disease_df[
        (disease_df['country'] == COUNTRY_NAME) &
        (disease_df['year'].isin(years_to_process))
    ]['region_name'])

    # (disease_set이 standard_set의 부분집합이어야 함)
    verification_result = disease_set_processed - standard_mozambique_set
    print(f"검증 결과 (set()가 나와야 함): {verification_result}")

except NameError:
    print("오류: 'disease_df'가 메모리에 없습니다. 먼저 로드해주세요.")
except Exception as e:
    print(f"예상치 못한 오류 발생: {e}")

--- 모잠비크(Mozambique) 데이터 정리 시작 ---
1단계: 전체 연도 오타/표기법 통일 완료.

--- 2009년 데이터 집계 시작 ---
'2009 Maputo' 생성 완료 (Rate: 13.218556)

--- 2015년 데이터 집계 시작 ---
'2015 Maputo' 생성 완료 (Rate: 19.634273)

3단계: 집계에 사용된 4개 행 삭제 완료.
가중 평균으로 집계된 새 'Maputo' 행 추가 완료.

--- [최종 작업 완료] 모잠비크(Mozambique) 데이터 정리 완료 ---

--- 검증 (2009, 2015년) ---
검증 결과 (set()가 나와야 함): set()

In [ ]:
disease_df[disease_df['country']=='Mozambique']

     year     country       region_name  infection_rate
25   2009  Mozambique      Cabo Delgado        6.680585
26   2009  Mozambique              Gaza       15.030675
27   2009  Mozambique         Inhambane        7.558946
28   2009  Mozambique            Manica       11.716058
29   2009  Mozambique     Maputo cidade       13.709677
30   2009  Mozambique  Maputo provincia       12.795436
31   2009  Mozambique           Nampula        3.123225
32   2009  Mozambique            Niassa        2.700831
33   2009  Mozambique            Sofala        9.320288
34   2009  Mozambique              Tete        4.548789
35   2009  Mozambique          Zambezia        8.721241
318  2015  Mozambique      Cabo delgado       12.650602
319  2015  Mozambique              Gaza       23.211781
320  2015  Mozambique         Inhambane       12.661738
321  2015  Mozambique            Manica       12.565445
322  2015  Mozambique     Maputo Cidade       15.754717
323  2015  Mozambique  Maputo Provincia       22.115385
324  2015  Mozambique           Nampula        4.935065
325  2015  Mozambique            Niassa        8.598131
326  2015  Mozambique            Sofala       15.652879
327  2015  Mozambique              Tete        7.034221
328  2015  Mozambique          Zambézia       12.948381

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="Niger"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="Niger"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="Niger"]['region_name'])))

niger_mapping_dict = {
    'Tillabéri':'Tillaberi'
}

disease_df.loc[disease_df['country'] == 'Niger', 'region_name'] = disease_df.loc[disease_df['country'] == 'Niger', 'region_name'].replace(niger_mapping_dict)

print("disease data after mapping")
new_niger_df = disease_df[disease_df['country']=='Niger']
print(new_niger_df)

set(new_niger_df['region_name']) - set(standard_df[standard_df['ADM0_NAME']=='Niger']['ADM1_NAME'])

disease region name
['Agadez', 'Diffa', 'Dosso', 'Maradi', 'Niamey', 'Tahoua', 'Tillaberi', 'Tillabéri', 'Zinder']

standard region name
['Agadez', 'Diffa', 'Dosso', 'Maradi', 'Niamey', 'Tahoua', 'Tillaberi', 'Zinder']



mismatch list
['Tillabéri']
disease data after mapping
     year country region_name  infection_rate
310  2006   Niger      Agadez        1.974612
311  2006   Niger       Diffa        1.608187
312  2006   Niger       Dosso        0.515021
313  2006   Niger      Maradi        0.391389
314  2006   Niger      Niamey        1.477833
315  2006   Niger      Tahoua        1.022147
316  2006   Niger   Tillaberi        0.465983
317  2006   Niger      Zinder        0.583431
360  2012   Niger      Agadez        0.733945
361  2012   Niger       Diffa        0.834327
362  2012   Niger       Dosso        0.411184
363  2012   Niger      Maradi        0.248911
364  2012   Niger      Niamey        1.152482
365  2012   Niger      Tahoua        0.608365
366  2012   Niger   Tillaberi        0.177305
367  2012   Niger      Zinder        0.195312

set()

In [ ]:
until_niger_df = disease_df

##**Rwanda**

#### **mapping pair**
- 'Kigali':'Kigali City/Umujyi wa Kigali',
- 'Kigali City':'Kigali City/Umujyi wa Kigali',
- 'East':'East/Iburasirazuba'

#### **특이사항**
- 2006년 도시명 전면 개편이 이루어져 2005년 데이터는 매핑하기 어려웠기에 삭제하였음

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="Rwanda"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="Rwanda"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="Rwanda"]['region_name'])))

# 1. 삭제할 조건 정의: "country가 'Rwanda'이고, 동시에 year가 2005"
condition_to_delete = (disease_df['country'] == 'Rwanda') & (disease_df['year'] == 2005)

# 2. 이 조건에 해당하지 않는(~) 모든 행만 남겨서 덮어씁니다.
disease_df = disease_df[~condition_to_delete]

rwanda_mapping_dict = {
    'Kigali':'Kigali City/Umujyi wa Kigali',
    'Kigali City':'Kigali City/Umujyi wa Kigali',
    'East':'East/Iburasirazuba'
}

disease_df.loc[disease_df['country'] == 'Rwanda', 'region_name'] = disease_df.loc[disease_df['country'] == 'Rwanda', 'region_name'].replace(rwanda_mapping_dict)

print("disease data after mapping")
new_rwanda_df = disease_df[disease_df['country']=='Rwanda']
print(new_rwanda_df)

set(new_rwanda_df['region_name']) - set(standard_df[standard_df['ADM0_NAME']=='Rwanda']['ADM1_NAME'])

disease region name
['Butare', 'Byumba', 'Cyangugu', 'East', 'Gikongoro', 'Gisenyi', 'Gitarama', 'Kibungo', 'Kibuye', 'Kigali', 'Kigali City', 'Kigali Ngali', 'Ruhengeri', 'Umutara', 'Ville de Kigali']

standard region name
['East/Iburasirazuba', 'Kigali City/Umujyi wa Kigali', 'North/Amajyaruguru', 'South/Amajyepfo', 'West/Iburengerazuba']



mismatch list
['Butare', 'Byumba', 'Cyangugu', 'East', 'Gikongoro', 'Gisenyi', 'Gitarama', 'Kibungo', 'Kibuye', 'Kigali', 'Kigali City', 'Kigali Ngali', 'Ruhengeri', 'Umutara', 'Ville de Kigali']
disease data after mapping
     year country                   region_name  infection_rate
329  2014  Rwanda            East/Iburasirazuba       17.918314
330  2014  Rwanda  Kigali City/Umujyi wa Kigali       14.285714
331  2010  Rwanda            East/Iburasirazuba        2.223634
332  2010  Rwanda  Kigali City/Umujyi wa Kigali        7.436709
409  2019  Rwanda            East/Iburasirazuba        2.560330
410  2019  Rwanda  Kigali City/Umujyi wa Kigali        4.124861

set()

In [ ]:
disease_df[disease_df['country']=='Rwanda']

     year country      region_name  infection_rate
329  2014  Rwanda             East       17.918314
330  2014  Rwanda      Kigali City       14.285714
331  2010  Rwanda             East        2.223634
332  2010  Rwanda      Kigali City        7.436709
333  2005  Rwanda           Butare        2.873563
334  2005  Rwanda           Byumba        1.803833
335  2005  Rwanda         Cyangugu        4.104104
336  2005  Rwanda        Gikongoro        1.815981
337  2005  Rwanda          Gisenyi        3.271028
338  2005  Rwanda         Gitarama        3.232999
339  2005  Rwanda          Kibungo        3.214696
340  2005  Rwanda           Kibuye        3.899371
341  2005  Rwanda     Kigali Ngali        2.771363
342  2005  Rwanda        Ruhengeri        2.542373
343  2005  Rwanda          Umutara        1.899441
344  2005  Rwanda  Ville de Kigali        7.370518
409  2019  Rwanda             East        2.560330
410  2019  Rwanda           Kigali        4.124861

In [ ]:
until_rwanda_df = disease_df

##**Sao Tome and Principe**

#### **mapping pair**
- Região Centro + Região Norte + Região Sul -(가중평균)-> Sao Tome
- Região do Principe -> Principe

#### **특이사항**

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="Sao Tome and Principe"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="Sao Tome and Principe"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="Sao Tome and Principe"]['region_name'])))

disease region name
['Região Centro', 'Região Norte', 'Região Sul', 'Região do Principe']

standard region name
['Principe', 'Sao Tome']



mismatch list
['Região Centro', 'Região Norte', 'Região Sul', 'Região do Principe']

In [ ]:
disease_df[disease_df['country']=='Sao Tome and Principe']

     year                country         region_name  infection_rate
405  2008  Sao Tome and Principe       Região Centro        1.292825
406  2008  Sao Tome and Principe        Região Norte        1.711712
407  2008  Sao Tome and Principe          Região Sul        1.070336
408  2008  Sao Tome and Principe  Região do Principe        2.793296

In [ ]:
# --- 1. 설정: 국가, 연도, 인구 ---
COUNTRY_NAME = 'Sao Tome and Principe' # (disease_df에 있는 정확한 이름으로 수정)
YEAR = 2008

population_2008_saotome = {
    'Região Norte': 48000,
    'Região Centro': 65000,
    'Região Sul': 29000
}

print(f"--- 상투메 프린시페({COUNTRY_NAME}) {YEAR}년 데이터 정리 시작 ---")

try:
    # --- 2. [3:1 집계] 'Sao Tome' 가중 평균 ---
    # (Norte + Centro + Sul -> Sao Tome)

    regions_to_aggregate = ['Região Norte', 'Região Centro', 'Região Sul']
    new_region_name = 'Sao Tome' # Standard 이름

    # 2008년 & 상투메 & 3개 지역 데이터 필터링
    df_parts = disease_df[
        (disease_df['country'] == COUNTRY_NAME) &
        (disease_df['year'] == YEAR) &
        (disease_df['region_name'].isin(regions_to_aggregate))
    ]

    new_row_df = pd.DataFrame() # 빈 DataFrame으로 시작

    if len(df_parts) == 3:
        # 2008년 인구 기반으로 가중 평균 계산
        pop_A = population_2008_saotome['Região Norte']
        rate_A = df_parts.loc[df_parts['region_name'] == 'Região Norte', 'infection_rate'].iloc[0]

        pop_B = population_2008_saotome['Região Centro']
        rate_B = df_parts.loc[df_parts['region_name'] == 'Região Centro', 'infection_rate'].iloc[0]

        pop_C = population_2008_saotome['Região Sul']
        rate_C = df_parts.loc[df_parts['region_name'] == 'Região Sul', 'infection_rate'].iloc[0]

        total_cases = (rate_A * pop_A) + (rate_B * pop_B) + (rate_C * pop_C)
        total_pop = pop_A + pop_B + pop_C
        new_rate = total_cases / total_pop

        # 새 행 생성
        new_row = {
            'country': COUNTRY_NAME,
            'year': YEAR,
            'region_name': new_region_name,
            'infection_rate': new_rate
        }
        new_row_df = pd.DataFrame([new_row])
        print(f"1단계: '{YEAR} {new_region_name}' 생성 완료 (Rate: {new_rate:.6f})")
    else:
        print(f"1단계 경고: {YEAR}년 3개 권역(Norte, Centro, Sul) 데이터가 모두 없습니다. 집계를 건너뜁니다.")

    # --- 3. 불필요한 행 삭제 ---
    # (집계에 사용된 3개 지역)
    indices_to_drop = disease_df[
        (disease_df['country'] == COUNTRY_NAME) &
        (disease_df['year'] == YEAR) &
        (disease_df['region_name'].isin(regions_to_aggregate))
    ].index

    disease_df = disease_df.drop(indices_to_drop)
    print(f"2단계: {YEAR}년 비표준 행 {len(indices_to_drop)}개 삭제 완료.")

    # --- 4. 새 집계 행 추가 ---
    if not new_row_df.empty:
        disease_df = pd.concat([disease_df, new_row_df], ignore_index=True)

    # --- 5. 단순 이름 매핑 (1:1 Rename) ---
    # ('Região do Principe' -> 'Principe')
    mapping_dict_saotome = {
        'Região do Principe': 'Principe'
    }

    mask = (disease_df['country'] == COUNTRY_NAME) & (disease_df['year'] == YEAR)
    disease_df.loc[mask, 'region_name'] = disease_df.loc[mask, 'region_name'].replace(mapping_dict_saotome)
    print("3단계: 1:1 단순 이름 매핑(Rename) 완료.")

    print(f"\n--- [최종 작업 완료] 상투메 프린시페({COUNTRY_NAME}) 데이터 정리 완료 ---")

    # --- 6. 검증 ---
    print("\n--- 검증 (2008년) ---")
    standard_saotome_set = set(['Principe', 'Sao Tome'])
    disease_set_2008 = set(disease_df[(disease_df['country'] == COUNTRY_NAME) & (disease_df['year'] == YEAR)]['region_name'])

    verification_result = disease_set_2008 - standard_saotome_set
    print(f"검증 결과 (set()가 나와야 함): {verification_result}")

except NameError:
    print("오류: 'disease_df'가 메모리에 없습니다. 먼저 로드해주세요.")
except KeyError as e:
    print(f"오류: 컬럼 이름({e})을 찾을 수 없습니다. 'infection_rate' 컬럼이 맞는지 확인하세요.")
except Exception as e:
    print(f"예상치 못한 오류 발생: {e}")

--- 상투메 프린시페(Sao Tome and Principe) 2008년 데이터 정리 시작 ---
1단계: '2008 Sao Tome' 생성 완료 (Rate: 1.388983)
2단계: 2008년 비표준 행 3개 삭제 완료.
3단계: 1:1 단순 이름 매핑(Rename) 완료.

--- [최종 작업 완료] 상투메 프린시페(Sao Tome and Principe) 데이터 정리 완료 ---

--- 검증 (2008년) ---
검증 결과 (set()가 나와야 함): set()

In [ ]:
until_sao_df = disease_df

##**Senegal**

#### **mapping pair**
- 'Saint-Louis':'Saint louis'
- 'Thiès':'Thies'
- 'Thiés':'Thies'
- 'Zuguinchor':'Ziguinchor'

#### **특이사항**

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="Senegal"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="Senegal"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="Senegal"]['region_name'])))

senegal_mapping_dict = {
    'Saint-Louis':'Saint louis',
    'Thiès':'Thies',
    'Thiés':'Thies',
    'Zuguinchor':'Ziguinchor'
}

disease_df.loc[disease_df['country'] == 'Senegal', 'region_name'] = disease_df.loc[disease_df['country'] == 'Senegal', 'region_name'].replace(senegal_mapping_dict)

print("disease data after mapping")
new_senegal_df = disease_df[disease_df['country']=='Senegal']
print(new_senegal_df)

set(new_senegal_df['region_name']) - set(standard_df[standard_df['ADM0_NAME']=='Senegal']['ADM1_NAME'])

disease region name
['Dakar', 'Diourbel', 'Fatick', 'Kaffrine', 'Kaolack', 'Kedougou', 'Kolda', 'Louga', 'Matam', 'Saint-Louis', 'Sedhiou', 'Tambacounda', 'Thiès', 'Thiés', 'Ziguinchor', 'Zuguinchor']

standard region name
['Dakar', 'Diourbel', 'Fatick', 'Kaffrine', 'Kaolack', 'Kedougou', 'Kolda', 'Louga', 'Matam', 'Saint louis', 'Sedhiou', 'Tambacounda', 'Thies', 'Ziguinchor']



mismatch list
['Saint-Louis', 'Thiès', 'Thiés', 'Zuguinchor']
disease data after mapping
     year  country  region_name  infection_rate
354  2017  Senegal        Dakar        0.353607
355  2017  Senegal     Diourbel        0.300903
356  2017  Senegal       Fatick        0.357462
357  2017  Senegal     Kaffrine        1.088032
358  2017  Senegal      Kaolack        0.551876
359  2017  Senegal     Kedougou        0.892857
360  2017  Senegal        Kolda        1.518027
361  2017  Senegal        Louga        0.493583
362  2017  Senegal        Matam        0.682927
363  2017  Senegal  Saint louis        0.300000
364  2017  Senegal      Sedhiou        0.537153
365  2017  Senegal  Tambacounda        0.824931
366  2017  Senegal        Thies        0.223547
367  2017  Senegal   Ziguinchor        1.488095
368  2010  Senegal        Dakar        0.416233
369  2010  Senegal     Diourbel        0.385604
370  2010  Senegal       Fatick        1.058201
371  2010  Senegal     Kaffrine        0.577201
372  2010  Senegal      Kaolack        1.272534
373  2010  Senegal     Kedougou        1.880878
374  2010  Senegal        Kolda        2.594034
375  2010  Senegal        Louga        0.268817
376  2010  Senegal        Matam        0.618238
377  2010  Senegal  Saint louis        0.796178
378  2010  Senegal      Sedhiou        1.234568
379  2010  Senegal  Tambacounda        1.447368
380  2010  Senegal        Thies        0.350467
381  2010  Senegal   Ziguinchor        1.190476
382  2005  Senegal        Dakar        0.682594
383  2005  Senegal     Diourbel        0.141844
384  2005  Senegal       Fatick        0.978793
385  2005  Senegal      Kaolack        0.828402
386  2005  Senegal        Kolda        1.903553
387  2005  Senegal        Louga        0.521739
388  2005  Senegal        Matam        0.713012
389  2005  Senegal  Saint louis        0.519931
390  2005  Senegal  Tambacounda        0.280899
391  2005  Senegal        Thies        0.339367
392  2005  Senegal   Ziguinchor        2.186589

set()

In [ ]:
until_senegal_df = disease_df

##**Sierra Leone**

#### **mapping pair**
- north western + northen -(가중평균)-> northen
- western : western area

#### **특이사항**

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="Sierra Leone"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="Sierra Leone"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="Sierra Leone"]['region_name'])))

sierra_mapping_dict = {
    'Western':'Western Area'
}

disease_df.loc[disease_df['country'] == 'Sierra Leone', 'region_name'] = disease_df.loc[disease_df['country'] == 'Sierra Leone', 'region_name'].replace(sierra_mapping_dict)

print("disease data after mapping")
new_sierra_df = disease_df[disease_df['country']=='Sierra Leone']
print(new_sierra_df)

set(new_sierra_df['region_name']) - set(standard_df[standard_df['ADM0_NAME']=='Sierra Leone']['ADM1_NAME'])

disease region name
['Eastern', 'North Western', 'Northern', 'Southern', 'Western']

standard region name
['Eastern', 'Northern', 'Southern', 'Western Area']



mismatch list
['North Western', 'Western']
disease data after mapping
     year       country    region_name  infection_rate
341  2013  Sierra Leone        Eastern        1.517707
342  2013  Sierra Leone       Northern        1.228324
343  2013  Sierra Leone       Southern        1.226680
344  2013  Sierra Leone   Western Area        2.649538
345  2019  Sierra Leone        Eastern        1.248734
346  2019  Sierra Leone  North Western        1.675332
347  2019  Sierra Leone       Northern        1.812977
348  2019  Sierra Leone       Southern        1.380138
349  2019  Sierra Leone   Western Area        2.689152
350  2008  Sierra Leone        Eastern        1.487911
351  2008  Sierra Leone       Northern        1.092044
352  2008  Sierra Leone       Southern        0.947603
353  2008  Sierra Leone   Western Area        2.817919

{'North Western'}

In [ ]:
# --- 1. 설정: 국가, 연도, 인구 ---
COUNTRY_NAME = 'Sierra Leone'
YEAR = 2019

# 2019년 신규 2개 주의 추정 인구 (가중 평균용)
# (2015년 센서스 기반 2019년 추정치)
population_2019_sierraleone = {
    'Northern': 1055000,     # (새롭고 작아진 Northern)
    'North Western': 1186000 # (신설된 North Western)
}

print(f"--- 시에라리온({COUNTRY_NAME}) {YEAR}년 데이터 집계 시작 ---")

try:
    # --- 2. [2:1 집계] 'Northern' (Old) 가중 평균 ---
    # (Northern(New) + North Western(New) -> Northern(Old))

    regions_to_aggregate = ['Northern', 'North Western']
    new_region_name = 'Northern' # Standard의 "낡은" 이름

    # 2019년 & 시에라리온 & 2개 지역 데이터 필터링
    df_parts = disease_df[
        (disease_df['country'] == COUNTRY_NAME) &
        (disease_df['year'] == YEAR) &
        (disease_df['region_name'].isin(regions_to_aggregate))
    ]

    new_row_df = pd.DataFrame() # 빈 DataFrame으로 시작

    if len(df_parts) == 2:
        # 2019년 인구 기반으로 가중 평균 계산
        pop_A = population_2019_sierraleone['Northern']
        rate_A = df_parts.loc[df_parts['region_name'] == 'Northern', 'infection_rate'].iloc[0]

        pop_B = population_2019_sierraleone['North Western']
        rate_B = df_parts.loc[df_parts['region_name'] == 'North Western', 'infection_rate'].iloc[0]

        total_cases = (rate_A * pop_A) + (rate_B * pop_B)
        total_pop = pop_A + pop_B
        new_rate = total_cases / total_pop

        # 새 행 생성 (standard의 낡은 이름 'Northern' 사용)
        new_row = {
            'country': COUNTRY_NAME,
            'year': YEAR,
            'region_name': new_region_name,
            'infection_rate': new_rate
        }
        new_row_df = pd.DataFrame([new_row])
        print(f"1단계: '{YEAR} {new_region_name}' (Old) 생성 완료 (Rate: {new_rate:.6f})")
    else:
        print(f"1단계 경고: {YEAR}년 Northern/North Western 데이터가 2개가 아닙니다. 집계를 건너뜁니다.")

    # --- 3. 불필요한 2019년 행 삭제 ---
    # (집계에 사용된 2개 지역)
    indices_to_drop = disease_df[
        (disease_df['country'] == COUNTRY_NAME) &
        (disease_df['year'] == YEAR) &
        (disease_df['region_name'].isin(regions_to_aggregate))
    ].index

    disease_df = disease_df.drop(indices_to_drop)
    print(f"2단계: {YEAR}년 비표준 행 {len(indices_to_drop)}개 삭제 완료.")

    # --- 4. 새 집계 행 추가 ---
    if not new_row_df.empty:
        disease_df = pd.concat([disease_df, new_row_df], ignore_index=True)

    # (참고: 2008년, 2013년의 'Northern' 행은 "낡은" 기준이므로 롤백이 필요 없으며
    #  standard와 1:1 매핑되므로 그대로 둡니다.)

    print(f"\n--- [최종 작업 완료] 시에라리온({COUNTRY_NAME}) 데이터 정리 완료 ---")

except NameError:
    print("오류: 'disease_df'가 메모리에 없습니다. 먼저 로드해주세요.")
except Exception as e:
    print(f"예상치 못한 오류 발생: {e}")

--- 시에라리온(Sierra Leone) 2019년 데이터 집계 시작 ---
1단계: '2019 Northern' (Old) 생성 완료 (Rate: 1.740132)
2단계: 2019년 비표준 행 2개 삭제 완료.

--- [최종 작업 완료] 시에라리온(Sierra Leone) 데이터 정리 완료 ---

In [ ]:
set(disease_df[disease_df['country']=="Sierra Leone"]['region_name']) - set(standard_df[standard_df['ADM0_NAME']=='Sierra Leone']['ADM1_NAME'])

set()

In [ ]:
disease_df[disease_df['country']=='Sierra Leone']

     year       country    region_name  infection_rate
341  2013  Sierra Leone        Eastern        1.517707
342  2013  Sierra Leone       Northern        1.228324
343  2013  Sierra Leone       Southern        1.226680
344  2013  Sierra Leone        Western        2.649538
345  2019  Sierra Leone        Eastern        1.248734
346  2019  Sierra Leone  North Western        1.675332
347  2019  Sierra Leone       Northern        1.812977
348  2019  Sierra Leone       Southern        1.380138
349  2019  Sierra Leone        Western        2.689152
350  2008  Sierra Leone        Eastern        1.487911
351  2008  Sierra Leone       Northern        1.092044
352  2008  Sierra Leone       Southern        0.947603
353  2008  Sierra Leone        Western        2.817919

In [ ]:
until_sierra_df = disease_df

##**South Africa, Togo**

#### **mapping pair**
- south africa
  - 'Kwazulu-Natal':'KwaZulu-Natal'
- togo
  - Grande Agglomération de Lomé + Maritime (Sans Agglomération de Lomé) -(가중평균)-> Maritime

#### **특이사항**

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="South Africa"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="South Africa"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="South Africa"]['region_name'])))

sa_mapping_dict = {
    'Kwazulu-Natal':'KwaZulu-Natal'
}

disease_df.loc[disease_df['country'] == 'South Africa', 'region_name'] = disease_df.loc[disease_df['country'] == 'South Africa', 'region_name'].replace(sa_mapping_dict)

print("disease data after mapping")
new_sa_df = disease_df[disease_df['country']=='South Africa']
print(new_sa_df)

set(new_sa_df['region_name']) - set(standard_df[standard_df['ADM0_NAME']=='South Africa']['ADM1_NAME'])

disease region name
['Eastern Cape', 'Free State', 'Gauteng', 'Kwazulu-Natal', 'Limpopo', 'Mpumalanga', 'North West', 'Northern Cape', 'Western Cape']

standard region name
['Eastern Cape', 'Free State', 'Gauteng', 'KwaZulu-Natal', 'Limpopo', 'Mpumalanga', 'North West', 'Northern Cape', 'Western Cape']



mismatch list
['Kwazulu-Natal']
disease data after mapping
     year       country    region_name  infection_rate
496  2016  South Africa   Eastern Cape       17.424242
497  2016  South Africa     Free State       21.083628
498  2016  South Africa        Gauteng       18.750000
499  2016  South Africa  KwaZulu-Natal       26.892430
500  2016  South Africa        Limpopo       10.306748
501  2016  South Africa     Mpumalanga       23.404255
502  2016  South Africa     North West       20.937841
503  2016  South Africa  Northern Cape       11.258278
504  2016  South Africa   Western Cape       11.335013

set()

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="Togo"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="Togo"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="Togo"]['region_name'])))

disease region name
['Centrale', 'Grande Agglomération de Lomé', 'Kara', 'Maritime (Sans Agglomération de Lomé)', 'Plateaux', 'Savanes']

standard region name
['Centrale', 'Kara', 'Maritime', 'Plateaux', 'Savanes']



mismatch list
['Grande Agglomération de Lomé', 'Maritime (Sans Agglomération de Lomé)']

In [ ]:
# --- 1. 설정: 국가, 연도, 인구 ---
COUNTRY_NAME = 'Togo'
YEAR = 2013

# 2013년 인구 데이터 (가중 평균용)
population_2013_togo = {
    'Grande Agglomération de Lomé': 1477000,
    'Maritime (Sans Agglomération de Lomé)': 1083000
}

print(f"--- 토고({COUNTRY_NAME}) {YEAR}년 데이터 집계 시작 ---")

try:
    # --- 2. [2:1 집계] 'Maritime' 가중 평균 ---
    # (Lomé + Maritime(Sans Lomé) -> Maritime)

    regions_to_aggregate = ['Grande Agglomération de Lomé', 'Maritime (Sans Agglomération de Lomé)']
    new_region_name = 'Maritime' # Standard 이름

    # 2013년 & 토고 & 2개 지역 데이터 필터링
    df_parts = disease_df[
        (disease_df['country'] == COUNTRY_NAME) &
        (disease_df['year'] == YEAR) &
        (disease_df['region_name'].isin(regions_to_aggregate))
    ]

    new_row_df = pd.DataFrame() # 빈 DataFrame으로 시작

    if len(df_parts) == 2:
        # 2013년 인구 기반으로 가중 평균 계산
        pop_A = population_2013_togo['Grande Agglomération de Lomé']
        rate_A = df_parts.loc[df_parts['region_name'] == 'Grande Agglomération de Lomé', 'infection_rate'].iloc[0]

        pop_B = population_2013_togo['Maritime (Sans Agglomération de Lomé)']
        rate_B = df_parts.loc[df_parts['region_name'] == 'Maritime (Sans Agglomération de Lomé)', 'infection_rate'].iloc[0]

        total_cases = (rate_A * pop_A) + (rate_B * pop_B)
        total_pop = pop_A + pop_B
        new_rate = total_cases / total_pop

        # 새 행 생성
        new_row = {
            'country': COUNTRY_NAME,
            'year': YEAR,
            'region_name': new_region_name,
            'infection_rate': new_rate
        }
        new_row_df = pd.DataFrame([new_row])
        print(f"1단계: '{YEAR} {new_region_name}' 생성 완료 (Rate: {new_rate:.6f})")
    else:
        print(f"1단계 경고: {YEAR}년 2개 권역(Lomé, Maritime(Sans...)) 데이터가 모두 없습니다. 집계를 건너뜁니다.")

    # --- 3. 불필요한 2013년 행 삭제 ---
    # (집계에 사용된 2개 지역)
    indices_to_drop = disease_df[
        (disease_df['country'] == COUNTRY_NAME) &
        (disease_df['year'] == YEAR) &
        (disease_df['region_name'].isin(regions_to_aggregate))
    ].index

    disease_df = disease_df.drop(indices_to_drop)
    print(f"2단계: {YEAR}년 비표준 행 {len(indices_to_drop)}개 삭제 완료.")

    # --- 4. 새 집계 행 추가 ---
    if not new_row_df.empty:
        disease_df = pd.concat([disease_df, new_row_df], ignore_index=True)

    # (참고: 'Centrale', 'Kara' 등 다른 4개 지역은 이름이 이미 standard와 일치하므로
    #  별도의 1:1 매핑 딕셔너리가 필요 없습니다.)

    print(f"\n--- [최종 작업 완료] 토고({COUNTRY_NAME}) 데이터 정리 완료 ---")

    # --- 5. 검증 ---
    print("\n--- 검증 (2013년) ---")
    standard_togo_set = set(['Centrale', 'Kara', 'Maritime', 'Plateaux', 'Savanes'])
    disease_set_2013 = set(disease_df[(disease_df['country'] == COUNTRY_NAME) & (disease_df['year'] == YEAR)]['region_name'])

    verification_result = disease_set_2013 - standard_togo_set
    print(f"검증 결과 (set()가 나와야 함): {verification_result}")

except NameError:
    print("오류: 'disease_df'가 메모리에 없습니다. 먼저 로드해주세요.")
except Exception as e:
    print(f"예상치 못한 오류 발생: {e}")

--- 토고(Togo) 2013년 데이터 집계 시작 ---
1단계: '2013 Maritime' 생성 완료 (Rate: 3.350563)
2단계: 2013년 비표준 행 2개 삭제 완료.

--- [최종 작업 완료] 토고(Togo) 데이터 정리 완료 ---

--- 검증 (2013년) ---
검증 결과 (set()가 나와야 함): set()

In [ ]:
disease_df[disease_df['country']=='Togo']

     year country                            region_name  infection_rate
464  2013    Togo                               Centrale        2.058824
465  2013    Togo           Grande Agglomération de Lomé        3.655108
466  2013    Togo                                   Kara        1.533966
467  2013    Togo  Maritime (Sans Agglomération de Lomé)        2.935223
468  2013    Togo                               Plateaux        2.210275
469  2013    Togo                                Savanes        0.389755

In [ ]:
until_togo_df = disease_df

##**Uganda**

#### **mapping pair**


#### **특이사항**
1. standard region name (112개) - 공식 행정 구역
- 2011년 기준 우간다의 가장 기본적인 행정 단위인 **'구역(Districts)'**

- 정부 행정, 인구 조사, 선거 등 국가의 공식적인 통계가 이루어지는 기준

2. disease region name (10개) - 통계 및 보고용 '광역 지역'
- 112개의 세부 구역(Districts)을 통계 분석 및 보고의 편의를 위해 10개의 더 큰 그룹으로 묶은 것
- 우간다 보건부(Ministry of Health)나 통계청(UBOS) 등에서 데이터를 관리하고 정책을 수립하기 위해 사용하는 '통계 지역(Statistical Regions)' 또는 '보건 지역(Health Regions)' 구분일 가능성이 매우 높음

=> 10개의 질병 데이터를 shapefile 기준으로 112개의 지역으로 발병률을 쪼개서 집계하기는 어렵기에 2011년 우간다 데이터는 삭제함

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="Uganda"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="Uganda"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="Uganda"]['region_name'])))

disease region name
['Central 1', 'Central 2', 'East Central', 'Kampala', 'Mid Eastern', 'Mid Northern', 'Mid Western', 'North East', 'South Western', 'West Nile']

standard region name
['Abim', 'Adjumani', 'Agago', 'Alebtong', 'Amolatar', 'Amudat', 'Amuria', 'Amuru', 'Apac', 'Arua', 'Budaka', 'Bududa', 'Bugiri', 'Buhweju', 'Buikwe', 'Bukedea', 'Bukomansimbi', 'Bukwo', 'Bulambuli', 'Buliisa', 'Bundibugyo', 'Bushenyi', 'Busia', 'Butaleja', 'Butambala', 'Buvuma', 'Buyende', 'Dokolo', 'Gomba', 'Gulu', 'Hoima', 'Ibanda', 'Iganga', 'Isingiro', 'Jinja', 'Kaabong', 'Kabale', 'Kabarole', 'Kaberamaido', 'Kalangala', 'Kaliro', 'Kalungu', 'Kampala', 'Kamuli', 'Kamwenge', 'Kanungu', 'Kapchorwa', 'Kasese', 'Katakwi', 'Kayunga', 'Kibaale', 'Kibuku', 'Kiruhura', 'Kiryandongo', 'Kisoro', 'Kitgum', 'Koboko', 'Kole', 'Kotido', 'Kumi', 'Kween', 'Kyankwanzi', 'Kyegegwa', 'Kyenjojo', 'Lamwo', 'Lira', 'Luuka', 'Luwero', 'Lwengo', 'Lyantonde', 'Manafwa', 'Maracha', 'Masaka', 'Masindi', 'Mayuge', 'Mbale', 'Mbarara', 'Mitooma', 'Mityana', 'Moroto', 'Moyo', 'Mpigi', 'Mubende', 'Mukono', 'Nakapiripirit', 'Nakaseke', 'Nakasongola', 'Namayingo', 'Namutumba', 'Napak', 'Nebbi', 'Ngora', 'Ntoroko', 'Ntungamo', 'Nwoya', 'Otuke', 'Oyam', 'Pader', 'Pallisa', 'Rakai', 'Rubirizi', 'Rukungiri', 'Serere', 'Sheema', 'Sironko', 'Soroti', 'Ssembabule', 'Tororo', 'Wakiso', 'Yumbe', 'Zombo']



mismatch list
['Central 1', 'Central 2', 'East Central', 'Mid Eastern', 'Mid Northern', 'Mid Western', 'North East', 'South Western', 'West Nile']

In [ ]:
disease_df[disease_df['country']=='Uganda']

     year country    region_name  infection_rate
424  2011  Uganda      Central 1        7.551020
425  2011  Uganda      Central 2        6.031746
426  2011  Uganda   East Central        3.753971
427  2011  Uganda        Kampala        6.167558
428  2011  Uganda    Mid Eastern        2.933709
429  2011  Uganda   Mid Northern        5.995651
430  2011  Uganda    Mid Western        5.486929
431  2011  Uganda     North East        3.834408
432  2011  Uganda  South Western        5.958188
433  2011  Uganda      West Nile        3.203173

In [ ]:
delete_condition = (disease_df['country']=='Uganda')
disease_df = disease_df[~delete_condition]

In [ ]:
disease_df[disease_df['country']=='Uganda']

Empty DataFrame
Columns: [year, country, region_name, infection_rate]
Index: []

In [ ]:
until_uganda_df = disease_df

##**United Republic of Tanzania**

#### **mapping pair**


#### **특이사항**
-2003년,2007년, 2011년 데이터(21개 지역)는 모두 2012년 이후 개편된 30개의 표준 지역보다 더 상위의, 덜 세분화된 집계입니다.

  - 행정구역 분리 (Administrative Splits):

    - 2003년 데이터의 Iringa (감염률 11.39)는 2012년에 Njombe 지역이 분리되기 이전의 더 큰 지역입니다. 데이터를 '쪼개는' 행위는 통계적으로 부정확합니다.

  - 누락된 지역 (Missing Regions):
    - 2003년 데이터(21개)는 탄자니아 본토(Mainland)만 포함하며, 5개의 잔지바르(Zanzibar) 지역(Kaskazini Pemba, Kusini Unguja 등)이 아예 없습니다. standard 목록은 이 5개 지역을 포함하므로, 이 지역들은 매핑할 원본 데이터 자체가 존재하지 않습니다.

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="United Republic of Tanzania"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="United Republic of Tanzania"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="United Republic of Tanzania"]['region_name'])))

tanzania_mapping_dict = {
    'Dar es Salaam':'Dar es salaam',
    'Kaskazini':'Kaskazini Unguja',
    'Kusini':'Kusini Unguja',

}

disease region name
['Arusha', 'Dar es Salaam', 'Dodoma', 'Geita', 'Iringa', 'Kagera', 'Kaskazini', 'Kaskazini Pemba', 'Katavi', 'Kigoma', 'Kilimanjaro', 'Kusini', 'Kusini Pemba', 'Lindi', 'Manyara', 'Mara', 'Mbeya', 'Mjini Magharibi', 'Morogoro', 'Mtwara', 'Mwanza', 'Njombe', 'Pemba 1', 'Pemba 2', 'Pwani', 'Rukwa', 'Ruvuma', 'Shinyanga', 'Simiyu', 'Singida', 'Tabora', 'Tanga', 'Unguja 1', 'Unguja 2', 'Unguja 3']

standard region name
['Arusha', 'Dar es salaam', 'Dodoma', 'Geita', 'Iringa', 'Kagera', 'Kaskazini Pemba', 'Kaskazini Unguja', 'Katavi', 'Kigoma', 'Kilimanjaro', 'Kusini Pemba', 'Kusini Unguja', 'Lindi', 'Manyara', 'Mara', 'Mbeya', 'Mjini Magharibi', 'Morogoro', 'Mtwara', 'Mwanza', 'Njombe', 'Pwani', 'Rukwa', 'Ruvuma', 'Shinyanga', 'Simiyu', 'Singida', 'Tabora', 'Tanga']



mismatch list
['Dar es Salaam', 'Kaskazini', 'Kusini', 'Pemba 1', 'Pemba 2', 'Unguja 1', 'Unguja 2', 'Unguja 3']

In [ ]:
print(sorted(set(disease_df[(disease_df['country']=='United Republic of Tanzania')&(disease_df['year']==2003)]['region_name'])))
print(sorted(set(disease_df[(disease_df['country']=='United Republic of Tanzania')&(disease_df['year']==2007)]['region_name'])))
print(sorted(set(disease_df[(disease_df['country']=='United Republic of Tanzania')&(disease_df['year']==2011)]['region_name'])))

['Arusha', 'Dar es Salaam', 'Dodoma', 'Iringa', 'Kagera', 'Kigoma', 'Kilimanjaro', 'Lindi', 'Manyara', 'Mara', 'Mbeya', 'Morogoro', 'Mtwara', 'Mwanza', 'Pwani', 'Rukwa', 'Ruvuma', 'Shinyanga', 'Singida', 'Tabora', 'Tanga']
['Arusha', 'Dar es Salaam', 'Dodoma', 'Iringa', 'Kagera', 'Kigoma', 'Kilimanjaro', 'Lindi', 'Manyara', 'Mara', 'Mbeya', 'Morogoro', 'Mtwara', 'Mwanza', 'Pemba 1', 'Pemba 2', 'Pwani', 'Rukwa', 'Ruvuma', 'Shinyanga', 'Singida', 'Tabora', 'Tanga', 'Unguja 1', 'Unguja 2', 'Unguja 3']
['Arusha', 'Dar es Salaam', 'Dodoma', 'Geita', 'Iringa', 'Kagera', 'Kaskazini', 'Kaskazini Pemba', 'Katavi', 'Kigoma', 'Kilimanjaro', 'Kusini', 'Kusini Pemba', 'Lindi', 'Manyara', 'Mara', 'Mbeya', 'Mjini Magharibi', 'Morogoro', 'Mtwara', 'Mwanza', 'Njombe', 'Pwani', 'Rukwa', 'Ruvuma', 'Shinyanga', 'Simiyu', 'Singida', 'Tabora', 'Tanga']

In [ ]:
disease_df[disease_df['country']=='United Republic of Tanzania']

     year                      country    region_name  infection_rate
34   2003  United Republic of Tanzania         Arusha        4.309064
35   2003  United Republic of Tanzania  Dar es Salaam        6.382979
36   2003  United Republic of Tanzania         Dodoma        3.594771
37   2003  United Republic of Tanzania         Iringa       11.392405
38   2003  United Republic of Tanzania         Kagera        3.583618
..    ...                          ...            ...             ...
489  2007  United Republic of Tanzania         Tabora        6.446281
490  2007  United Republic of Tanzania          Tanga        5.555556
491  2007  United Republic of Tanzania       Unguja 1        0.326264
492  2007  United Republic of Tanzania       Unguja 2        1.197605
493  2007  United Republic of Tanzania       Unguja 3        1.051248

[77 rows x 4 columns]

     year                country        region_name  infection_rate
0    2010           Burkina Faso  Boucle Du Mouhoun        0.585652
1    2010           Burkina Faso           Cascades        0.979432
2    2010           Burkina Faso             Centre        1.955671
3    2010           Burkina Faso         Centre-est        1.037736
4    2010           Burkina Faso        Centre-nord        0.379147
..    ...                    ...                ...             ...
572  2009             Mozambique             Maputo       13.218556
573  2015             Mozambique             Maputo       19.634273
574  2008  Sao Tome and Principe           Sao Tome        1.388983
575  2019           Sierra Leone           Northern        1.740132
576  2013                   Togo           Maritime        3.350563

[567 rows x 4 columns]

In [ ]:
delete_condition = (disease_df['country']=='United Republic of Tanzania')
disease_df = disease_df[~delete_condition]

In [ ]:
disease_df[disease_df['country']=='United Republic of Tanzania']

Empty DataFrame
Columns: [year, country, region_name, infection_rate]
Index: []

In [ ]:
until_tanzania_df = disease_df

##**Zambia**

#### **mapping pair**
- Muchinga + Northern -(가중평균)-> Northern
- 'North Western' : 'North-Western'

#### **특이사항**

In [ ]:
# disease 데이터에서의 region name
print('disease region name')
print(sorted(set(disease_df[disease_df['country']=="Zambia"]['region_name'])))
# standard 데이터에서의 region name
print('\nstandard region name')
print(sorted(set(standard_df[standard_df['ADM0_NAME']=="Zambia"]['ADM1_NAME'])))


# disease와 standard에서 불일치하는 region name(disease 이름 기준)
print('\n\n\nmismatch list')
print(sorted(set(mismatch_df[mismatch_df['country']=="Zambia"]['region_name'])))

disease region name
['Central', 'Copperbelt', 'Eastern', 'Luapula', 'Lusaka', 'North-Western', 'Northern', 'Southern', 'Western']

standard region name
['Central', 'Copperbelt', 'Eastern', 'Luapula', 'Lusaka', 'North-Western', 'Northern', 'Southern', 'Western']



mismatch list
['Muchinga', 'North Western']

In [ ]:
disease_df[disease_df['country']=='Zambia']

     year country    region_name  infection_rate
394  2018  Zambia        Central       14.285714
395  2018  Zambia     Copperbelt       21.365360
396  2018  Zambia        Eastern       17.537313
397  2018  Zambia        Luapula       14.592275
398  2018  Zambia         Lusaka       17.918314
399  2018  Zambia       Muchinga       14.417532
400  2018  Zambia  North Western       19.215686
401  2018  Zambia       Northern       18.549747
402  2018  Zambia       Southern       12.857143
403  2018  Zambia        Western       16.504854
414  2013  Zambia        Central       13.145161
415  2013  Zambia     Copperbelt       17.220052
416  2013  Zambia        Eastern       11.972753
417  2013  Zambia        Luapula       14.011181
418  2013  Zambia         Lusaka       16.003387
419  2013  Zambia       Muchinga        8.923885
420  2013  Zambia  North Western        8.612613
421  2013  Zambia       Northern       12.366667
422  2013  Zambia       Southern       13.944099
423  2013  Zambia        Western       19.119609

In [ ]:
# --- 1. 설정: 국가, 연도, 인구 ---
COUNTRY_NAME = 'Zambia'
YEARS_TO_PROCESS = [2013, 2018] # 처리할 연도 목록

# 2013년, 2018년 인구 (2010/2022년 인구 조사 기반 선형 보간 추정치)
population_data_by_year = {
    2013: {
        'Muchinga': 763317,
        'Northern': 1233971
    },
    2018: {
        'Muchinga': 849416,
        'Northern': 1447549
    }
}

print(f"--- 잠비아({COUNTRY_NAME}) [2013, 2018] 데이터 표준화 시작 ---")

# (오류 방지) disease_df가 존재하는지 확인
try:
    # disease_df의 존재 여부 확인 (데이터프레임인지)
    if not isinstance(disease_df, pd.DataFrame):
        print("오류: 'disease_df'가 DataFrame이 아닙니다. 먼저 로드해주세요.")
        raise NameError("'disease_df'가 정의되지 않음")

    # --- 2. 연도별(2013, 2018) 표준화 작업 반복 ---
    for year in YEARS_TO_PROCESS:

        print(f"\n--- {year}년 데이터 처리 시작 ---")

        # 해당 연도의 인구 데이터 가져오기
        population_data = population_data_by_year.get(year)
        if population_data is None:
            print(f"1단계 경고: {year}년 인구 데이터가 없습니다. 이 연도를 건너뜁니다.")
            continue

        # --- 2-1. [2:1 집계] 'Northern' 가중 평균 ---
        # (Muchinga + Northern -> Northern)

        regions_to_aggregate = ['Muchinga', 'Northern']
        new_region_name = 'Northern' # Standard 이름

        # 해당 연도, 국가, 2개 지역 데이터 필터링
        df_parts = disease_df[
            (disease_df['country'] == COUNTRY_NAME) &
            (disease_df['year'] == year) &
            (disease_df['region_name'].isin(regions_to_aggregate))
        ]

        new_row_df = pd.DataFrame() # 새 행을 담을 빈 DataFrame

        if len(df_parts) == 2:
            # 2개 지역이 모두 존재하면 가중 평균 계산
            pop_A = population_data['Muchinga']
            rate_A = df_parts.loc[df_parts['region_name'] == 'Muchinga', 'infection_rate'].iloc[0]

            pop_B = population_data['Northern']
            rate_B = df_parts.loc[df_parts['region_name'] == 'Northern', 'infection_rate'].iloc[0]

            total_cases = (rate_A * pop_A) + (rate_B * pop_B)
            total_pop = pop_A + pop_B
            new_rate = total_cases / total_pop

            # 새 행 생성
            new_row = {
                'country': COUNTRY_NAME,
                'year': year,
                'region_name': new_region_name, # 'Northern'
                'infection_rate': new_rate
            }
            new_row_df = pd.DataFrame([new_row])
            print(f"1단계: '{year} {new_region_name}' 생성 완료 (Rate: {new_rate:.6f})")

        elif len(df_parts) == 0:
            print(f"1단계 정보: {year}년 집계 대상(Muchinga, Northern)이 없습니다. 건너뜁니다.")
        else:
            print(f"1단계 경고: {year}년 2개 권역(Muchinga, Northern) 중 1개만 존재합니다. 집계를 건너뜁니다.")

        # --- 2-2. 불필요한 원본 행 삭제 ---
        # (df_parts에 있던 'Muchinga', 'Northern' 행)
        indices_to_drop = df_parts.index

        if len(indices_to_drop) > 0:
            disease_df = disease_df.drop(indices_to_drop)
            print(f"2단계: {year}년 비표준 행 {len(indices_to_drop)}개 삭제 완료.")
        # (집계할 행이 없었으면 삭제도 하지 않음)

        # --- 2-3. 새 집계 행 추가 ---
        if not new_row_df.empty:
            disease_df = pd.concat([disease_df, new_row_df], ignore_index=True)

        # --- 2-4. [1:1 매핑] 이름 수정 ---
        # ('North Western' -> 'North-Western')
        condition = (
            (disease_df['country'] == COUNTRY_NAME) &
            (disease_df['year'] == year) &
            (disease_df['region_name'] == 'North Western')
        )

        num_replaced = len(disease_df.loc[condition])
        if num_replaced > 0:
            disease_df.loc[condition, 'region_name'] = 'North-Western'
            print(f"3단계: 1:1 매핑 'North Western' -> 'North-Western' {num_replaced}건 처리 완료.")
        else:
            print(f"3단계: 1:1 매핑 대상('North Western')이 없습니다.")

    # --- 3. (루프 종료 후) 최종 검증 ---
    print(f"\n--- [최종 작업 완료] 잠비아({COUNTRY_NAME}) 데이터 정리 완료 ---")

    print(f"\n--- 검증 (처리된 연도: {YEARS_TO_PROCESS}) ---")
    standard_zambia_set = set(['Central', 'Copperbelt', 'Eastern', 'Luapula', 'Lusaka', 'North-Western', 'Northern', 'Southern', 'Western'])

    # 처리된 연도들의 지역명만 가져오기
    disease_set_processed = set(disease_df[
        (disease_df['country'] == COUNTRY_NAME) &
        (disease_df['year'].isin(YEARS_TO_PROCESS))
    ]['region_name'])

    # 표준 셋(standard_zambia_set)에 없는 지역명이 있는지 확인
    verification_result = disease_set_processed - standard_zambia_set
    print(f"표준 셋에 없는 지역명 (비어 있어야 함): {verification_result if verification_result else '없음'}")

    if not verification_result:
        print("✅ 검증 통과: 모든 지역명이 표준과 일치합니다.")
    else:
        print(f"⚠️ 검증 실패: {verification_result} 지역명이 표준화되지 않았습니다.")


# --- 4. (try...except) 오류 처리 ---
except NameError:
    # 'disease_df'가 정의되지 않았을 때
    print("오류: 'disease_df'가 메모리에 없습니다. 먼저 로드해주세요.")
except KeyError as e:
    # 'population_data_by_year' 딕셔너리에 'Muchinga' 또는 'Northern' 키가 없을 때
    print(f"오류: 인구 데이터 딕셔너리에 필요한 키가 없습니다: {e}")
except IndexError:
    # .iloc[0]을 호출했으나 데이터가 없을 때 (df_parts 로직이 잘못되었을 경우)
    print(f"오류: {year}년 데이터 필터링 중 인덱싱 오류가 발생했습니다.")
except Exception as e:
    # 기타 모든 예외
    print(f"예상치 못한 오류 발생: {e}")

--- 잠비아(Zambia) [2013, 2018] 데이터 표준화 시작 ---

--- 2013년 데이터 처리 시작 ---
1단계: '2013 Northern' 생성 완료 (Rate: 11.050915)
2단계: 2013년 비표준 행 2개 삭제 완료.
3단계: 1:1 매핑 'North Western' -> 'North-Western' 1건 처리 완료.

--- 2018년 데이터 처리 시작 ---
1단계: '2018 Northern' 생성 완료 (Rate: 17.021657)
2단계: 2018년 비표준 행 2개 삭제 완료.
3단계: 1:1 매핑 'North Western' -> 'North-Western' 1건 처리 완료.

--- [최종 작업 완료] 잠비아(Zambia) 데이터 정리 완료 ---

--- 검증 (처리된 연도: [2013, 2018]) ---
표준 셋에 없는 지역명 (비어 있어야 함): 없음
✅ 검증 통과: 모든 지역명이 표준과 일치합니다.

In [ ]:
final_disease_df = disease_df

In [ ]:
final_disease_df

     year                country        region_name  infection_rate
0    2010           Burkina Faso  Boucle Du Mouhoun        0.585652
1    2010           Burkina Faso           Cascades        0.979432
2    2010           Burkina Faso             Centre        1.955671
3    2010           Burkina Faso         Centre-est        1.037736
4    2010           Burkina Faso        Centre-nord        0.379147
..    ...                    ...                ...             ...
483  2008  Sao Tome and Principe           Sao Tome        1.388983
484  2019           Sierra Leone           Northern        1.740132
485  2013                   Togo           Maritime        3.350563
486  2013                 Zambia           Northern       11.050915
487  2018                 Zambia           Northern       17.021657

[488 rows x 4 columns]

# **최종 질병 데이터셋**

csv 변환하여 내보내기

In [ ]:
final_disease_df.to_csv('processed_HIV_rates.csv', index=False)